### ISSUE TITLE
Maps delete themselves when I reload the server

### ISSUE THREAD

**Issue by DeTOB69** [ScreamingSandals/BedWars#102]
Hello, im having an issue with the bedwars plugin. Everything works great at first. I set up a map and save it. That all goies as intended, bet when I try to join the map, it gives me an internal error. And when I reload the server or restart it, the map doesnt exist anymore, all the configurations are just gone. I found this error while starting up the server:

[21:09:25] [Server thread/ERROR]: Error occurred while enabling BedWars v0.2.4 (Is it up to date?)
java.lang.NullPointerException
	at org.screamingsandals.bedwars.lib.sgui.SimpleGuiFormat.generateData(SimpleGuiFormat.java:383) ~[?:?]
	at org.screamingsandals.bedwars.inventories.ShopInventory.loadNewShop(ShopInventory.java:274) ~[?:?]
	at org.screamingsandals.bedwars.inventories.ShopInventory.<init>(ShopInventory.java:136) ~[?:?]
	at org.screamingsandals.bedwars.Main.onEnable(Main.java:437) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

What would I need to do to solve this? Im using spigot 1.9.4

**Comment by Misat11** [comment]
you have some mistake in your shop.yml, send me it please

**Comment by DeTOB69** [comment]
# +----------------------------------------------------+
# <                    Shop-Config                     >
# <                                                    >
# <                  buy for the price                 >
# <               sell for the sell item               >
# <           Item-ids http://bit.ly/1v9kw0X           >
# <              Default item-amount is 1              >
# <             Data http://bit.ly/YjzQeX              >
# <  Name supports color codes http://bit.ly/1rpIbZI   >
# <  Lore supports color codes http://bit.ly/1rpIbZI   >
# <       Enchantments {enchantment-id}:{level}        >
# <               http://bit.ly/1t2gxPb                >
# +----------------------------------------------------+

shop:
  blocks:
    id: 24
    name: '&fBlocks'
    lore:
    - Protect against the opponents
    offers:
      '1':
        buy:
          type: bronze
          amount: 1
        sell:
          id: 24
          amount: 2
      '2':
        buy:
          type: bronze
          amount: 7
        sell:
          id: 121
      '3':
        buy:
          type: iron
          amount: 1
        sell:
          id: 42
      '4':
        buy:
          type: bronze
          amount: 15
        sell:
          id: 89
          amount: 4
      '5':
        buy:
          type: bronze
          amount: 4
        sell:
          id: 20
  armor:
    id: 303
    name: '&bArmor'
    lore:
    - Protect against the opponents
    offers:
      '1':
        buy:
          type: bronze
          amount: 1
        sell:
          id: 298
          ench:
          - 0:1
          - '34:1'
      '2':
        buy:
          type: bronze
          amount: 1
        sell:
          id: 300
          ench:
          - 0:1
          - '34:1'
      '3':
        buy:
          type: bronze
          amount: 1
        sell:
          id: 301
          ench:
          - 0:1
          - '34:1'
      '4':
        buy:
          type: bronze
          amount: 3
        sell:
          id: 334
      '5':
        buy:
          type: iron
          amount: 1
        sell:
          id: 303
          ench:
          - 0:1
          - '34:1'
      '6':
        buy:
          type: iron
          amount: 3
        sell:
          id: 303
          ench:
          - 0:2
          - '34:1'
      '7':
        buy:
          type: iron
          amount: 7
        sell:
          id: 303
          ench:
          - 0:3
          - '34:1'
  tools:
    id: 274
    name: '&eTools'
    lore:
    - Break from the blocks of the opponents
    - Also help you breaking down the bed
    offers:
      '1':
        buy:
          type: bronze
          amount: 4
        sell:
          id: 270
          ench:
          - '32:1'
          - '34:1'
      '2':
        buy:
          type: iron
          amount: 2
        sell:
          id: 274
          ench:
          - '32:1'
          - '34:1'
      '3':
        buy:
          type: gold
          amount: 1
        sell:
          id: 257
          ench:
          - '32:3'
          - '34:1'
  swords:
    id: 283
    name: '&4Swords'
    lore:
    - Attack your opponents and nudge them down
    offers:
      '1':
        buy:
          type: bronze
          amount: 8
        sell:
          id: 280
          name: '&b&oCudgel'
          ench:
          - '19:1'
      '2':
        buy:
          type: iron
          amount: 1
        sell:
          id: 283
          ench:
          - '16:1'
          - '34:1'
      '3':
        buy:
          type: iron
          amount: 3
        sell:
          id: 283
          ench:
          - '16:2'
          - '34:1'
      '4':
        buy:
          type: gold
          amount: 5
        sell:
          id: 267
          ench:
          - '16:2'
          - '34:2'
          - '19:1'
  bows:
    id: 261
    name: '&aBows'
    lore:
    - Shoot your enemies from their blocks
    offers:
      '1':
        buy:
          type: gold
          amount: 3
        sell:
          id: 261
          name: '&bBOW LVL 1'
          ench:
          - '51:1'
      '2':
        buy:
          type: gold
          amount: 7
        sell:
          id: 261
          name: '&bBOW LVL 2'
          ench:
          - '51:1'
          - '48:1'
      '3':
        buy:
          type: gold
          amount: 13
        sell:
          id: 261
          name: '&bBOW LVL 3'
          ench:
          - '51:1'
          - '48:1'
          - '49:1'
      '4':
        buy:
          type: gold
          amount: 1
        sell:
          id: 262
  food:
    id: 260
    name: '&9Food'
    lore:
    - With food you can satisfy your hunger
    - Important to restore life
    offers:
      '1':
        buy:
          type: bronze
          amount: 1
        sell:
          id: 260
      '2':
        buy:
          type: bronze
          amount: 2
        sell:
          id: 320
      '3':
        buy:
          type: iron
          amount: 1
        sell:
          id: 354
      '4':
        buy:
          type: gold
          amount: 3
        sell:
          id: 322
  chests:
    id: 54
    name: '&5Chests'
    lore:
    - In boxes you can gather recources
    offers:
      '1':
        buy:
          type: iron
          amount: 1
        sell:
          id: 54
      '2':
        buy:
          type: gold
          amount: 1
        sell:
          id: 130
          name: Teamchest
  potions:
    id: 373
    name: '&bPotions'
    lore:
    - Use potions to give yourself advantages
    offers:
      '1':
        buy:
          type: iron
          amount: 3
        sell:
          id: 373
          data: 8261
      '2':
        buy:
          type: iron
          amount: 5
        sell:
          id: 373
          data: 8229
      '3':
        buy:
          type: iron
          amount: 7
        sell:
          id: 373
          data: 8194
      '4':
        buy:
          type: gold
          amount: 8
        sell:
          id: 373
          data: 8201
  special:
    id: 46
    name: '&6Special'
    lore:
    - Nice things which you can use absolutely sometimes
    offers:
      '1':
        buy:
          type: bronze
          amount: 1
        sell:
          id: 65
      '2':
        buy:
          type: bronze
          amount: 16
        sell:
          id: 30
      '4':
        buy:
          type: iron
          amount: 3
        sell:
          id: 289
          name: Warp Powder
      '5':
        buy:
          type: iron
          amount: 5
        sell:
          id: 287
          name: Trap
      '6':
        buy:
          type: iron
          amount: 2
        sell:
          id: 346
      '7':
        buy:
          type: iron
          amount: 1
        sell:
          id: 259
      '8':
        buy:
          type: gold
          amount: 3
        sell:
          id: 46
      '9':
        buy:
          type: gold
          amount: 13
        sell:
          id: 368
      '10':
        buy:
          type: gold
          amount: 3
        sell:
          id: 369
          name: Safety Platform
      '11':
        buy:
          type: gold
          amount: 18
        sell:
          id: 385
          name: Gravity grenade
      '12':
        buy:
          type: iron
          amount: 10
        sell:
          id: 345
          name: Player tracker


Git wont allow me to upload the file, so here is the raw text

**Comment by DeTOB69** [comment]
[shop.txt](https://github.com/ScreamingSandals/BedWars/files/4009642/shop.txt)
ok, here it is

**Comment by Misat11** [comment]
1) This is not shop.yml in valid format (it's from another plugin), 2) use pastebin and send link for future

**Comment by DeTOB69** [comment]
I also found a new error in my logs:

[21:13:09] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BedWars v0.2.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at org.screamingsandals.bedwars.Main.getGameWithHighestPlayers(Main.java:581) ~[?:?]
	at org.screamingsandals.bedwars.commands.JoinCommand.execute(JoinCommand.java:33) ~[?:?]
	at org.screamingsandals.bedwars.commands.BwCommandsExecutor.onCommand(BwCommandsExecutor.java:72) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
	... 15 more

**Comment by Misat11** [comment]
you have another bedwars plugin before this?

**Comment by DeTOB69** [comment]
Yes, I did
The original bedwars reloaded and this one: https://dev.bukkit.org/projects/bedwars

**Comment by DeTOB69** [comment]
The original bedwars reloaded had the same problem

**Comment by Misat11** [comment]
remove shop.yml and any other files copied from BedwarsRel and restart server. These plugins aren't compatible

**Comment by DeTOB69** [comment]
The problem still persists

**Comment by DeTOB69** [comment]
![image](https://user-images.githubusercontent.com/59361785/71580477-27263b00-2b01-11ea-9ed3-c2c0d7aa9b23.png)
I dont know if it helps, but here is a list of my plugins

**Comment by Misat11** [comment]
make you sure you're working with folder Bedwars and not BedwarsRel

**Comment by DeTOB69** [comment]
![image](https://user-images.githubusercontent.com/59361785/71580627-c21f1500-2b01-11ea-823e-bdc75d938696.png)

BEdwars is the only folder as far as I can see

**Comment by Misat11** [comment]
ok and did you remove your shop.yml file and did you restart tge server?

**Comment by DeTOB69** [comment]
Yes

**Comment by Misat11** [comment]
so what's currebt error on server start?

**Comment by DeTOB69** [comment]
Well, strangely enough, i dont see any errors, here's the log though:
[latest (1).log](https://github.com/ScreamingSandals/BedWars/files/4009713/latest.1.log)

I initiated the reload command a couple of times

**Comment by Misat11** [comment]
so maybe you don't have any arena file, try setting arena again and use `/bw arena <arenaName> save` for save

**Comment by DeTOB69** [comment]
Everything works now! Thank you so much for reacting so fast!
