### ISSUE TITLE
Cant enable Bedwars

### ISSUE THREAD

**Issue by MarekkXD** [ScreamingSandals/BedWars#183]
#### Server and plugin version
Spigot version: 1.14.4
BedWars version: 0.2.7

#### Installed plugins on server 
BkCommonLib - 1.14.4
CommandSigns
Essentials
Minigameslib
My_Worlds
Vault
WorldEdit

#### Console log
[BedWars] Enabling BedWars v0.2.7
[10:49:30] [Server thread/INFO]: [BedWars] Successfully loaded messages for BedWars! Language: English
[10:49:30] [Server thread/INFO]: [BedWars] Loading statistics from YAML-File ...
[10:49:31] [Server thread/ERROR]: Error occurred while enabling BedWars v0.2.7 (Is it up to date?)
java.lang.NullPointerException: null
at org.screamingsandals.bedwars.lib.sgui.utils.StackParser.parseLongStack(StackParser.java:277) ~[?:?]
at org.screamingsandals.bedwars.lib.sgui.utils.StackParser.parse(StackParser.java:46) ~[?:?]
at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.generateItem(SimpleInventories.java:699) ~[?:?]
at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.generateItem(SimpleInventories.java:881) ~[?:?]
at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.generateData(SimpleInventories.java:317) ~[?:?]
at org.screamingsandals.bedwars.inventories.ShopInventory.loadNewShop(ShopInventory.java:283) ~[?:?]
at org.screamingsandals.bedwars.inventories.ShopInventory.<init>(ShopInventory.java:141) ~[?:?]
at org.screamingsandals.bedwars.Main.onEnable(Main.java:450) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

#### Configuration (of config.yml and shop.yml)
data:
#-   stack:
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

- stack: "DIAMOND_CHESTPLATE;1;Armor;Protect yourself with armor! Click here."
  items:
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_HELMET
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
       PROTECTION_PROJECTILE: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 3 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 5 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
   - price: 9 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 3
       PROTECTION_PROJECTILE: 1

  
- stack: "DIAMOND_SWORD;1;Swords;Click here to get sword for attacking your enemies"
  column: center
  items:
   - price: 8 of bronze
     stack:
      type: STICK
      enchants:
       KNOCKBACK: 1
   - price: 12 of iron
     stack:
      type: STICK
      display-name: "Jebavka"
      enchants:
       KNOCKBACK: 3
   - price: 3 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 1
   - price: 5 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 2
   - price: 7 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 3
   - price: 5 of gold
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 3
       KNOCKBACK: 1
   - price: 12 of gold
     stack:
      type: GOLDEN_AXE
      display-name: "Axe of Infinity"
      enchants:
       DAMAGE_ALL: 2
       DURABILITY: 1
       KNOCKBACK: 1
   - price: 22 of gold
     stack:
      type: DIAMOND_AXE
      display-name: "Tomikov dick"
      enchants:
       DAMAGE_ALL: 4
       DURABILITY: 1
       
- stack: "BOW;1;Bows;Prove yourself as a marksman with these wonderful bows"
  column: right
  items:
   - price: 13 of iron
     stack:
      type: BOW
      enchants:
      ARROW_DAMAGE: 1
   - price: 8 of gold
     stack:
      type: BOW
      enchants:
       ARROW_DAMAGE: 2
   - price: 14 of gold
     stack:
      type: BOW
      enchants:
       ARROW_DAMAGE: 3
   - price: 17 of gold
     stack:
      type: BOW
      enchants:
       ARROW_DAMAGE: 3
       ARROW_FIRE: 1
   - price: 21 of gold
     stack:
      type: BOW
      enchants:
       ARROW_DAMAGE: 3
       ARROW_FIRE: 1
       ARROW_KNOCKBACK: 1
   - ARROW;5 for 2 of gold

- stack: "COOKED_PORKCHOP;1;Eat;Are you hungry? Get something to eat."
  row: 3
  column: 2
  items:
   - COOKED_PORKCHOP;2 for 4 of bronze
   - GOLDEN_APPLE for 2 of gold

- stack:
   type: POTION
   meta:
    ==: ItemMeta
    meta-type: POTION
    display-name: "Drinks"
    lore:
     - "Not enough? Use these potions and you'll feel better!"
    potion-type: strength
  row: 3
  column: 6
  items:
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: healing
     price: 3 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strong_healing
     price: 5 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: swiftness
     price: 7 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strength
     price: 1 of gold
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: regeneration
     price: 3 of gold

- stack: "SANDSTONE;1;Blocks;Get to the others! Possible with blocks."
  linebreak: before
  items:
   - CUT_SANDSTONE;2 for 1 of bronze
   - END_STONE;3 for 7 of bronze
   - IRON_BLOCK for 3 of iron
   - GLOWSTONE;4 for 15 of bronze
   - OBSIDIAN for 20 of gold
   - price: 4 of bronze
     properties: "applycolorbyteam"
     stack: GLASS

- stack: "TNT;1;Useful Stuff;Looking for useful stuff? Here are some!"
  column: center
  items:
   - CHEST for 1 of iron
   - ENDER_CHEST for 1 of gold
   - price: 7 of iron
     properties:
      - name: "WarpPowder"
        delay: 5
     stack:
      type: GUNPOWDER
      display-name: "Warp Powder"
      lore:
       - "When using this powder you'll get"
       - "teleported to you spawn point within 5 seconds"
       - "Warning: Any movement will stop the process"
   - price: 3 of iron
     properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
     stack:
      type: STRING
      display-name: "Trap"
      lore:
       - "Get informed if an enemy steps on your trap"
       - "and your enemy won't be able to move properly."
   - price: 6 of iron
     properties:
      - name: "MagnetShoes"
        probability: 75
     stack:
      type: IRON_BOOTS
      display-name: "Češkove ponožky"
      lore:
       - "Kec maš obute ta 75%"
       - "šanca že ti nedropne rank"
   - price: 5 of iron
     properties: "Tracker"
     stack:
      type: COMPASS
      display-name: "Tracker"
      lore:
       - "Wanna know where your closest target is?"
       - "Let's try this out!"
   - price: 13 of iron
     properties:
      - name: "rescueplatform"
        delay: 5
     stack:
      type: BLAZE_ROD
      display-name: "Rescue Platform"
      lore:
       - "Protect yourself from falling into"
       - "void with a Rescue Platform."
       - "This is your last hope!"
   - price: 5 of gold
     properties:
      - name: "arrowblocker"
        delay: 5
     stack:
      type: ENDER_EYE
      display-name: "Arrow Blocker"
      lore:
       - "Block arrows that are coming"
       - "for you with black magic."
       - "I mean, with this item."
   - price: 64 of bronze
     properties:
      - name: "protectionwall"
     stack:
      type: BRICKS
      display-name: "Protection Wall"
      lore:
       - "Instantly builds a wall that"
       - "can save your life!"
   - price: 24 of iron
     properties:
      - name: "Golem"
        speed: 0.25
        follow: 16.0
     stack:
      type: GHAST_SPAWN_EGG
      display-name: "Golem"
      lore:
       - "An iron golem that will protect"
       - "your team from the enemies."
   - price: 10 of gold
     properties: "TNTSheep"
     stack:
      type: SHEEP_SPAWN_EGG
      display-name: "TNT Sheep"
      lore:
       - "Use the TNT-Sheep! It will"
       - "walk towards your closest enemy"
       - "and explode within 8 seconds!"
   - price: 30 of iron
     properties: "ThrowableFireball"
     stack:
       type: FIRE_CHARGE
       display-name: "Fireball"
       lore:
         - "Is it a bird? Is it a plane?"
         - "By the time you know"
         - "you are dead!"
   - ENDER_PEARL for 24 of gold
   - SNOWBALL;12 for 6 of iron
   - price: 16 of bronze
     stack:
       type: IRON_INGOT
       display-name: "§7Iron"
   - price: 5 of iron
     stack:
       type: GOLD_INGOT
       display-name: "§6Gold"

- stack: "DIAMOND_PICKAXE;1;Pickaxes;Destroy others blocks? Use these pickaxes."
  column: right
  items:
   - price: 4 of bronze
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 1
   - price: 2 of iron
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 2
   - price: 1 of gold
     stack:
      type: DIAMOND_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 3
       DIG_SPEED: 1

locale: en
debug: false
allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: true
join-randomly-after-lobby-timeout: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: true
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: false
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: false
player-respawn-items: false
gived-game-start-items: []
gived-player-respawn-items: []
disable-hunger: false
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
destroy-placed-blocks-by-explosion-except: ''
destroy-placed-blocks-by-explosion: true
holo-above-bed: true
allow-spectator-join: false
disable-server-message: true
  player-join: false
  player-leave: false
respawn-cooldown:
  enabled: true
  time: 5
stop-team-spawners-on-die: false
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
  enabled: false
  serverRestart: true
  serverStop: false
  server: hub
  auto-game-connect: false
farmBlocks:
  enable: false
  blocks: []
scoreboard:
  enable: true
  title: §a%game%§r - %time%
  bedLost: §c✘
  bedExists: §a✔
  teamTitle: '%bed%%color%%team%'
title:
  fadeIn: 0
  stay: 20
  fadeOut: 0
items:
  jointeam: COMPASS
  leavegame: SLIME_BALL
  startgame: DIAMOND
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  team-select: WHITE_WOOL
vault:
  enable: true
  reward:
    kill: 5
    win: 20
resources:
  gold:
    material: GOLD_INGOT
    color: GOLD
    name: Gold
    interval: 20
    translate: resource_gold
    spread: 1.0
  iron:
    material: IRON_INGOT
    color: GRAY
    name: Iron
    interval: 10
    translate: resource_iron
    spread: 1.0
  bronze:
    material: BRICK
    color: DARK_RED
    name: Bronze
    interval: 1
    translate: resource_bronze
    spread: 1.0
respawn:
  protection-enabled: true
  protection-time: 10
specials:
  action-bar-messages: true
  rescue-platform:
    is-breakable: false
    delay: 0
    break-time: 10
    distance: 1
    material: GLASS
  protection-wall:
    is-breakable: false
    delay: 20
    break-time: 0
    width: 5
    height: 3
    distance: 2
    material: CUT_SANDSTONE
  tnt-sheep:
    speed: 2.0
    follow-range: 10.0
    max-target-distance: 32
    explosion-time: 8
  arrow-blocker:
    protection-time: 10
    delay: 5
  warp-powder:
    teleport-time: 6
    delay: 0
  magnet-shoes:
    probability: 75
  golem:
    speed: 0.25
    follow-range: 10
    health: 20
    name-format: '%teamcolor%%team% Golem'
    show-name: true
    delay: 0
    collidable: false
  teamchest:
    turn-all-enderchests-to-teamchests: true
  throwable-fireball:
    explosion: 3.0
tnt:
  auto-ignite: false
  explosion-time: 8
sounds:
  on_bed_destroyed: ENTITY_ENDER_DRAGON_GROWL
  on_countdown: UI_BUTTON_CLICK
  on_game_start: ENTITY_PLAYER_LEVELUP
  on_team_kill: ENTITY_PLAYER_LEVELUP
  on_player_kill: ENTITY_PLAYER_BIG_FALL
  on_item_buy: ENTITY_ITEM_PICKUP
  on_upgrade_buy: ENTITY_EXPERIENCE_ORB_PICKUP
  on_respawn_cooldown_wait: UI_BUTTON_CLICK
  on_respawn_cooldown_done: ENTITY_PLAYER_LEVELUP
game-effects:
  end:
    effects:
    - ==: Firework
      flicker: false
      trail: false
      colors:
      - &id001
        ==: Color
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id001
      type: BALL
    power: 1
    type: Firework
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
lobby-scoreboard:
  enabled: true
  title: §eBEDWARS
  content:
  - ' '
  - '§fMap: §2%arena%'
  - '§fPlayers: §2%players%§f/§2%maxplayers%'
  - ' '
  - §fWaiting ...
  - ' '
statistics:
  enabled: true
  type: yaml
  show-on-game-end: false
  bed-destroyed-kills: false
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
database:
  host: localhost
  port: 3306
  db: databse
  user: root
  password: secret
  table-prefix: bw_
bossbar:
  use-xp-bar: false
  lobby:
    enable: true
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: true
    color: GREEN
    style: SEGMENTED_20
holograms:
  enabled: true
  headline: Your §eBEDWARS§f stats
chat:
  override: true
  format: '<%teamcolor%%name%§r> '
  separate-chat:
    lobby: false
    game: false
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '@a'
  team-chat-prefix: '@t'
  all-chat: '[ALL] '
  team-chat: '[TEAM] '
  death-chat: '[DEATH] '
rewards:
  enabled: false
  player-win:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10
lore:
  generate-automatically: true
  text:
  - '§7Price:'
  - §7%price% %resource%
  - '§7Amount:'
  - §7%amount%
sign:
- §c§l[BedWars]
- '%arena%'
- '%status%'
- '%players%'
hotbar:
  selector: 0
  color: 1
  start: 2
  leave: 8
breakable:
  enabled: false
  asblacklist: false
  blocks: []
leaveshortcuts:
  enabled: false
  list:
  - leave
mainlobby:
  enabled: false
  location: ''
  world: ''
version: 2

**Comment by iamceph** [comment]
Not a bug, you have invalid shop.yml or shop.yml..

**Comment by iamceph** [comment]
Also, old version.

**Comment by MarekkXD** [comment]
But what is invalid.
About version, it worked just fine and suddenly it didnt

**Comment by iamceph** [comment]
I don't know, I can't magically see your configuration and look into it. The error is saying that you have something invalid in your shop or config.yml

**Comment by linusstretchtips** [comment]
lmao

**Comment by MarekkXD** [comment]
That is exactly what i am asking. I did some changes but i reverted most of them, writing looks absolutely fine and it just stopped working when i tried to re-enable it

**Comment by linusstretchtips** [comment]
put it through http://www.yamllint.com/

**Comment by linusstretchtips** [comment]
and check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html for material names

**Comment by iamceph** [comment]
Null pointer happens when something is null, like empty enchants: category and so on. This is not a bug

**Comment by MarekkXD** [comment]
Thank you!
Shop looked fine.
There was 1 problem in config where were blank spaces.
Hope it will work now. Will let you know.

**Comment by MarekkXD** [comment]
Well, still : 

> [22:13:53] [Server thread/INFO]: [BedWars] Enabling BedWars v0.2.7
> [22:14:01] [Server thread/INFO]: [BedWars] Successfully loaded messages for BedWars! Language: English
> [22:14:01] [Server thread/INFO]: [BedWars] Loading statistics from YAML-File ...
> [22:14:01] [Server thread/ERROR]: Error occurred while enabling BedWars v0.2.7 (Is it up to date?)
java.lang.NullPointerException: null
at org.screamingsandals.bedwars.lib.sgui.utils.StackParser.parseLongStack(StackParser.java:277) ~[?:?]
at org.screamingsandals.bedwars.lib.sgui.utils.StackParser.parse(StackParser.java:46) ~[?:?]
at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.generateItem(SimpleInventories.java:699) ~[?:?]
at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.generateItem(SimpleInventories.java:881) ~[?:?]
at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.generateData(SimpleInventories.java:317) ~[?:?]
at org.screamingsandals.bedwars.inventories.ShopInventory.loadNewShop(ShopInventory.java:283) ~[?:?]
at org.screamingsandals.bedwars.inventories.ShopInventory.<init>(ShopInventory.java:141) ~[?:?]
at org.screamingsandals.bedwars.Main.onEnable(Main.java:450) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [minecraft_server.jar:git-Spigot-cbd1a1b-009d8af]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by iamceph** [comment]
You have some error in your shop.yml. Probably empty enchants: shit or so on

**Comment by MarekkXD** [comment]
I have no idea, checked it like 5 times already but i really do not know.

**Comment by MarekkXD** [comment]
Can i find default shop from this version somewhere ?

**Comment by iamceph** [comment]
Delete current shop.yml, plugin will generate new one
