### ISSUE TITLE
Error on enabling plugin

### ISSUE THREAD

**Issue by irishgreencitrus** [ScreamingSandals/BedWars#257]
Bedwars fails to enable

Spigot version: patched_1.16.4.jar:git-Paper-350
BedWars version: 0.2.15

![image](https://user-images.githubusercontent.com/43090499/104324260-20395300-54df-11eb-8eaa-2083bcd69a0b.png)

[14:00:52 ERROR]: Error occurred while enabling BedWars v0.2.15 (Is it up to date?)
 java.lang.IllegalArgumentException: No enum constant org.bukkit.ChatColor.Green
         at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
         at org.bukkit.ChatColor.valueOf(ChatColor.java:14) ~[patched_1.16.4.jar:git-Paper-350]
         at org.screamingsandals.bedwars.Main.onEnable(Main.java:453) ~[?:?]
         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-350]
         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-350]
         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-350]
         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-350]
         at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-350]
         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-35>
         at java.lang.Thread.run(Thread.java:834) [?:?]
[14:00:52 INFO]: [BedWars] Disabling BedWars v0.2.15

**Comment by Misat11** [comment]
In your config.yml you have chat color Green, but valid is only GREEN
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
