### ISSUE TITLE
Plugin Not Loading

### ISSUE THREAD

**Issue by STRARKTECHNOLOGIES** [ScreamingSandals/BedWars#266]
Error log Is here 
[08:30:09 ERROR]: Error occurred while enabling BedWars v0.2.15 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.ChatColor.Green
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_282]
        at org.bukkit.ChatColor.valueOf(ChatColor.java:14) ~[patched_1.16.5.jar:git-Paper-457]
        at org.screamingsandals.bedwars.Main.onEnable(Main.java:453) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by iamceph** [comment]
Invalid color in your config, it GREEN.
