### ISSUE TITLE
failed to load arena 

### ISSUE THREAD

**Issue by starboy20000** [ScreamingSandals/BedWars#271]
#### Describe the bug
whenever I stop and turn it back on the server it says failed to load arena 
#### Server and plugin version
Spigot version:papper 471
BedWars version:0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
BedWars-0..15.jar
Citizens.jar
CitizensCMD.jar
EasyWarp.jar
floodgate-bukkit.jar
Geyser-Spigot.jar
HolographicDisplays.jar
IridiumSkyblock-2.6.7.jar
Multiverse-Core-4.2.2.jar
OldPVP.jar
SBAHypixelify-1.4.3-all.jar
SkyWarsReloaded-V1.7.jar
SuperVanish-6.2.0.jar
Vault.jar
ViaBackwards-3.2.0.jar
ViaRewind-1.5.3.jar
ViaVersion-3.2.1.jaro
worldedit-bukkit-7.2.2-dist.jar
worldguard-bukkit-7.0.4.jar
#### Console log
[17:18:51 WARN]: [BedWars] Something went wrong while loading arena file Amazon.yml. Please report this to our Discord or GitHub!
[17:18:51 WARN]: java.lang.NullPointerException
[17:18:51 WARN]:        at org.screamingsandals.bedwars.utils.MiscUtils.convertColorToNewFormat(MiscUtils.java:207)
[17:18:51 WARN]:        at org.screamingsandals.bedwars.game.Game.loadGame(Game.java:932)
[17:18:51 WARN]:        at org.screamingsandals.bedwars.game.Game.loadGame(Game.java:836)
[17:18:51 WARN]:        at org.screamingsandals.bedwars.Main.onEnable(Main.java:508)
[17:18:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:18:51 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[17:18:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[17:18:51 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500)
[17:18:51 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414)
[17:18:51 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465)
[17:18:51 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[17:18:51 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936)
[17:18:51 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[17:18:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
#### Configuration (of config.yml and shop.yml)
I didn't do any thing to the config 
#### If there are problem with only one game, paste here config of this game
failed to load arena

**Comment by Misat11** [comment]
In the tenplate there's last point: if there is problem with specific game, paste here config of this game. please send us the Amazon.yml file (via paste.gg/pastebin/hastebin)

**Comment by starboy20000** [comment]
https://paste.gg/p/starboy2000/d2228426779d48aba3b669767a55be72

**Comment by starboy20000** [comment]
have you found the problom

**Comment by pronze** [comment]
Do not use "." in a team name, this has caused incorrect serialization to the arena config file

**Comment by Misat11** [comment]
![image](https://user-images.githubusercontent.com/20199703/108882450-b09da400-7604-11eb-9eb3-ec9cbddeb317.png)
Well the
```yaml
Light:
  Blue:
  ```
  in the file is problem, idk how did you do it, but change it to
  ```yaml
  Light_Blue:
  ```

**Comment by starboy20000** [comment]
thank you you are the best
