### ISSUE TITLE
internalJoinPlayer Error NullPointer

### ISSUE THREAD

**Issue by Tobstr02** [ScreamingSandals/BedWars#301]
#### Describe the bug
The bug appears when joining a game. I guess it's the reason for that no one get a team automatically by joining.

#### Server and plugin version
Spigot version: PaperMC 1.16.4-1.16.5
BedWars version: 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
WorldEdit, WorldGuard, BedWars, eZProtector, OldCombatMechanics, LuckPerms

#### Console log
`[19:29:13] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BedWars v0.2.15
java.lang.NullPointerException: null
        at org.screamingsandals.bedwars.game.Game.lambda$internalJoinPlayer$9(Game.java:711) ~[?:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:538) ~[?:?]
        at org.screamingsandals.bedwars.game.Game.lambda$internalJoinPlayer$10(Game.java:711) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at org.screamingsandals.bedwars.game.Game.internalJoinPlayer(Game.java:710) ~[?:?]
        at org.screamingsandals.bedwars.game.GamePlayer.changeGame(GamePlayer.java:49) ~[?:?]
        at org.screamingsandals.bedwars.game.Game.joinToGame(Game.java:1311) ~[?:?]
        at org.screamingsandals.bedwars.utils.BedWarsSignOwner.onClick(BedWarsSignOwner.java:78) ~[?:?]
        at org.screamingsandals.bedwars.lib.signmanager.SignListener.onPlayerInteract(SignListener.java:34) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor343.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-566]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-566]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-566]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-566]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:531) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:498) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1698) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:31) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-566]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-566]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

#### Configuration (of config.yml and shop.yml)
Not needed i guess?

**Comment by pronze** [comment]
send the entire logs please

**Comment by Espantonius** [comment]
I have the same problem. Also when i step on a pressure plate i get a similar message: https://gist.github.com/Espantonius/d133f57f79d2df0ba72448d12764c521

Tested with:
Server: git-Paper-638 (MC: 1.16.5)
Plugin: 0.3.0-SNAPSHOT-797
Java: 11

**Comment by zlataovce** [comment]
@Espantonius don't use snapshots

**Comment by iamceph** [comment]
Update to latest  **stable** version.
