### ISSUE TITLE
error

### ISSUE THREAD

**Issue by giorno420** [ScreamingSandals/BedWars#313]
#### Describe the bug
**I did /bw mainlobby enable, then I did a /bw reload. After that, I did /bw mainlobby set
thats when the bedwars plugin just stopped and didn't respond**

#### Server and plugin version
Spigot version: **1.16.5**
BedWars version: **Latest**

#### Installed plugins on server (can be obtained by `/pl`)
**AdvancedBan, BedWars, ChatLock*, Citizens, CommandNPC*, CommandPanels, DiscordSRV, HolographicDisplays, ItemJoin, JumpPads, LoginSecurity*, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NametagEdit*, OldCombatMechanics, OpenInv, PlayerParticles, SBAHypixelify, SkinsRestorer, SkQuery, Skript, Skywars, SuperVanish, TabList, Vault, VaultChatFormatter*, VoidSpawn, WorldEdit, WorldGuard**
#### Console log
`[15:24:02 ERROR]: [BedWars] An unhandled exception was thrown during command execution
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:920) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
        at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1126) ~[?:?]
        at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-683]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-683]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-683]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at org.screamingsandals.bedwars.lib.ext.cloud.exceptions.parsing.NoInputProvidedException.<init>(NoInputProvidedException.java:49) ~[?:?]
        at org.screamingsandals.bedwars.lib.ext.cloud.arguments.StaticArgument$StaticArgumentParser.parse(StaticArgument.java:116) ~[?:?]
        at org.screamingsandals.bedwars.lib.ext.cloud.CommandTree.parseCommand(CommandTree.java:229) ~[?:?]
        at org.screamingsandals.bedwars.lib.ext.cloud.CommandTree.parseCommand(CommandTree.java:234) ~[?:?]
        at org.screamingsandals.bedwars.lib.ext.cloud.CommandTree.parse(CommandTree.java:136) ~[?:?]
        at org.screamingsandals.bedwars.lib.ext.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:114) ~[?:?]
        at org.screamingsandals.bedwars.lib.ext.cloud.CommandManager.executeCommand(CommandManager.java:176) ~[?:?]
        at org.screamingsandals.bedwars.lib.ext.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:91) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-683]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2176) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1991) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1944) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1217) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-683]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-683]
        at java.lang.Thread.run(Thread.java:834) [?:?]`
#### Configuration (of config.yml and shop.yml)
**Nothing was modified**

**Comment by iamceph** [comment]
We don't provide support for 0.3.x snapshots.
