### ISSUE TITLE
Error in Leaderboard and German Language

### ISSUE THREAD

**Issue by pthoelken** [ScreamingSandals/BedWars#324]
#### Describe the bug
Change language for  Bedwars. I've downloaded the german language file from here https://weblate.screamingsandals.org/download-language/de/bedwars/?format=zip and pasted into the json-files into the language plugin folder of Bedwars. 

After that I've change the locale to "de" and / or to "de-DE", (i've tried both) both are occured the problem below. No leaderboard is shown. 

#### Server and plugin version
Spigot version: 1.16.5
BedWars version: 0.2.15

#### Installed plugins on server (can be obtained by `/pl`)
![image](https://user-images.githubusercontent.com/12643853/122251289-a90f4d00-ceca-11eb-8800-ad27fc8cfb61.png)

#### Console log

```
[17:44:49] [Server thread/INFO]: DieCooleEnte issued server command: /bw addholo leaderboard
[17:44:49] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BedWars v0.2.15
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2312) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2127) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2080) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1350) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1343) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1159) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
	at java.lang.String.replace(String.java:2159) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.lambda$updateHologram$3(LeaderboardHolograms.java:130) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.updateHologram(LeaderboardHolograms.java:129) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.lambda$updateHolograms$2(LeaderboardHolograms.java:113) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.updateHolograms(LeaderboardHolograms.java:108) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.updateEntries(LeaderboardHolograms.java:43) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.addHologramLocation(LeaderboardHolograms.java:31) ~[?:?]
	at org.screamingsandals.bedwars.commands.AddholoCommand.execute(AddholoCommand.java:25) ~[?:?]
	at org.screamingsandals.bedwars.commands.BwCommandsExecutor.onCommand(BwCommandsExecutor.java:72) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
	... 19 more
```

#### Configuration (of config.yml and shop.yml)
config.yml : https://pastebin.com/raw/DMZiRc8v
shop.yml : https://pastebin.com/raw/xX2R7V0t

**Comment by zlataovce** [comment]
that language file is intended for the 0.3.0 version of sbw, the language files for sbw 0.2.15 are [here](https://github.com/ScreamingSandals/BedWars/tree/bd12385f7c2e349b76feb2760a0db6712b7b1763/plugin/src/main/resources/languages)

**Comment by pthoelken** [comment]
oh lord. Thanks. 

0.3.0 is in beta or alpha?

**Comment by zlataovce** [comment]
0.3.0 is not ready for usage, please use the stable 0.2.15 or try out the 0.2.16 beta [here](https://ci.screamingsandals.org/job/BW-0.2.16/8/artifact/plugin/build/libs/BedWars-0.2.16-SNAPSHOT-8.jar)

**Comment by pthoelken** [comment]
yea. Of course. I've used the latest build from spigotmc :-D Thanks for your help!

**Comment by pthoelken** [comment]
#

**Comment by pthoelken** [comment]
Sorry, but I think it's not fixed. I've downloaded the languagefile from your link and pasted it into the language folder and set locale to "de" in the config file. 

```
[08:34:42] [Server thread/INFO]: Running delayed init tasks
[08:34:42] [Server thread/ERROR]: [BedWars] Task #12 for BedWars v0.2.15 generated an exception
[08:34:42] [Server thread/ERROR]: [BedWars] Suspected Plugins: 
[08:34:42] [Server thread/ERROR]: [BedWars] 	BedWars{enabled,ver=0.2.15,path=plugins/BedWars-0.2.15.jar}
[08:34:42] [Server thread/ERROR]: [BedWars] Exception details below: 
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
	at java.lang.String.replace(String.java:2159) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.lambda$updateHologram$3(LeaderboardHolograms.java:130) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.updateHologram(LeaderboardHolograms.java:129) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.lambda$updateHolograms$2(LeaderboardHolograms.java:113) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.updateHolograms(LeaderboardHolograms.java:108) ~[?:?]
	at org.screamingsandals.bedwars.holograms.LeaderboardHolograms.updateEntries(LeaderboardHolograms.java:43) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1084) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[08:34:42] [Server thread/INFO]: Done (13.229s)! For help, type "help"
[08:34:42] [Server thread/INFO]: Timings Reset
[08:34:42] [Craft Scheduler Thread - 2 - SBAHypixelify/INFO]: No updates found
[08:34:56] [User Authenticator #1/INFO]: UUID of player Quentoo is a07e776e-d512-4304-a37e-d13783696682
[08:34:57] [Server thread/INFO]: Quentoo joined the game
[08:34:57] [Server thread/INFO]: Quentoo[/91.248.125.196:54431] logged in with entity id 1 at ([BedWars]-7.301397974185855, 64.0, 9.046565625573331)
[08:35:10] [Server thread/INFO]: Quentoo issued server command: /bw leaderboard
[08:35:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BedWars v0.2.15
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2267) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2082) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2035) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1336) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1329) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1305) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1145) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "replacement" is null
	at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1014) ~[?:?]
	at java.util.regex.Matcher.appendReplacement(Matcher.java:997) ~[?:?]
	at java.util.regex.Matcher.replaceAll(Matcher.java:1181) ~[?:?]
	at java.lang.String.replaceAll(String.java:2142) ~[?:?]
	at org.screamingsandals.bedwars.lib.lang.Message.get(Message.java:178) ~[?:?]
	at org.screamingsandals.bedwars.lib.lang.Message.get(Message.java:171) ~[?:?]
	at org.screamingsandals.bedwars.lib.lang.Message.send(Message.java:152) ~[?:?]
	at org.screamingsandals.bedwars.commands.LeaderboardCommand.lambda$execute$0(LeaderboardCommand.java:33) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.screamingsandals.bedwars.commands.LeaderboardCommand.execute(LeaderboardCommand.java:31) ~[?:?]
	at org.screamingsandals.bedwars.commands.BwCommandsExecutor.onCommand(BwCommandsExecutor.java:72) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-122]
	... 19 more

```

**Comment by zlataovce** [comment]
try to delete your statistics file and restart the server

**Comment by iamceph** [comment]
Update to latest version.
