### ISSUE TITLE
Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY

### ISSUE THREAD

**Issue by MrKayfer-gg** [ScreamingSandals/BedWars#328]
#### Describe the bug
This error occurs each time you start the server, and sometimes there is an error that means an error loading player data from the database (The server does not display holograms)

P.S. Perhaps the problem is that I'm trying to use with the plugin Russian characters?

#### Server and plugin version
Spigot version: PaperSpigot 1.17 #46
BedWars version: 0.2.17

#### Installed plugins on server

BedWars 0.2.17
Multiverse-Core 4.2.2
ProtocolLib 4.7.0-SNAPSHOT-b521
SecuredNetwork 3.1
ViaBackwards 4.0.0
ViaRewind 2.0.0
ViaVersion 4.0.0
WorldEdit 7.2.6-SNAPSHOT+5842-43da91a
WorldGuard 7.0.6-SNAPSHOT+2132-e88d8a5

#### Console log
[20:13:00] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:13:01] [main/INFO]: Reloading ResourceManager: Default, bukkit
[20:13:02] [Worker-Main-7/INFO]: Loaded 7 recipes
[20:13:03] [Server thread/INFO]: Starting minecraft server version 1.17
[20:13:03] [Server thread/INFO]: Loading properties
[20:13:03] [Server thread/INFO]: This server is running Paper version git-Paper-46 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 9e07703)
[20:13:04] [Server thread/INFO]: Debug logging is disabled
[20:13:04] [Server thread/INFO]: Using 4 threads for Netty based IO
[20:13:04] [Server thread/INFO]: Server Ping Player Sample Count: 0
[20:13:04] [Server thread/INFO]: Default game type: ADVENTURE
[20:13:04] [Server thread/INFO]: Generating keypair
[20:13:04] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25451
[20:13:04] [Server thread/INFO]: Using epoll channel type
[20:13:05] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.6-SNAPSHOT+5842-43da91a
[20:13:05] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@758d9e68]
[20:13:05] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v4.0.0
[20:13:05] [Server thread/INFO]: [ViaVersion] ViaVersion 4.0.0 is now loaded, injecting!
[20:13:06] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading 1.12 -> 1.13 mappings...
[20:13:06] [Via-Mappingloader-1/INFO]: [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
[20:13:06] [Via-Mappingloader-2/INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
[20:13:06] [Via-Mappingloader-3/INFO]: [ViaVersion] Loading 1.14 -> 1.15 mappings...
[20:13:06] [Via-Mappingloader-4/INFO]: [ViaVersion] Loading 1.15 -> 1.16 mappings...
[20:13:06] [Via-Mappingloader-5/INFO]: [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
[20:13:06] [Via-Mappingloader-6/INFO]: [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
[20:13:06] [Server thread/INFO]: [ViaBackwards] Loading ViaBackwards v4.0.0
[20:13:06] [Server thread/INFO]: [ViaBackwards] Loading translations...
[20:13:06] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[20:13:06] [Via-Mappingloader-1/INFO]: [ViaBackwards] Loading 1.10 -> 1.9.4 mappings...
[20:13:06] [Via-Mappingloader-3/INFO]: [ViaBackwards] Loading 1.11 -> 1.10 mappings...
[20:13:06] [Via-Mappingloader-6/INFO]: [ViaBackwards] Loading 1.13.2 -> 1.13 mappings...
[20:13:06] [Via-Mappingloader-6/INFO]: [ViaBackwards] Loading 1.14 -> 1.13.2 mappings...
[20:13:06] [Via-Mappingloader-5/INFO]: [ViaBackwards] Loading 1.13 -> 1.12 mappings...
[20:13:06] [Via-Mappingloader-5/INFO]: [ViaBackwards] Loading 1.15 -> 1.14 mappings...
[20:13:06] [Via-Mappingloader-5/INFO]: [ViaBackwards] Loading 1.16 -> 1.15 mappings...
[20:13:06] [Via-Mappingloader-6/INFO]: [ViaBackwards] Loading 1.16.2 -> 1.16 mappings...
[20:13:06] [Via-Mappingloader-6/INFO]: [ViaBackwards] Loading 1.17 -> 1.16.2 mappings...
[20:13:07] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.6-SNAPSHOT+2132-e88d8a5
[20:13:07] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v4.2.2-b812
[20:13:07] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.7.0-SNAPSHOT-b521
[20:13:08] [Server thread/INFO]: [ViaRewind] Loading ViaRewind v2.0.0
[20:13:08] [Server thread/INFO]: [BedWars] Loading BedWars v0.2.17
[20:13:08] [Server thread/INFO]: [SecuredNetwork] Loading SecuredNetwork v3.1
[20:13:08] [Server thread/INFO]: Server permissions file permission.yml is empty, ignoring it
[20:13:08] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.6-SNAPSHOT+5842-43da91a
[20:13:08] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[20:13:08] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[20:13:08] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1 as the Bukkit adapter
[20:13:10] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.7.0-SNAPSHOT-b521
[20:13:10] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[20:13:10] [Server thread/INFO]: [ViaRewind] Enabling ViaRewind v2.0.0
[20:13:10] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[20:13:10] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[20:13:10] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[20:13:10] [Server thread/WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[20:13:10] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[20:13:10] [Server thread/INFO]: Preparing level "world"
[20:13:10] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:13:12] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[20:13:12] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[20:13:12] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[20:13:12] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[20:13:12] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[20:13:13] [Server thread/INFO]: Time elapsed: 2268 ms
[20:13:13] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.0.0
[20:13:13] [Server thread/INFO]: [ViaBackwards] Enabling ViaBackwards v4.0.0
[20:13:13] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.6-SNAPSHOT+2132-e88d8a5
[20:13:13] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[20:13:13] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[20:13:13] [Server thread/INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[20:13:13] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[20:13:13] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[20:13:13] [Server thread/INFO]: [WorldGuard] Loading region data...
[20:13:13] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.2.2-b812
[20:13:13] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.2.2-b812" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
[20:13:13] [Server thread/INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
[20:13:13] [Server thread/INFO]: Preparing start region for dimension minecraft:mine
[20:13:16] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[20:13:16] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[20:13:16] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[20:13:16] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[20:13:16] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[20:13:16] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[20:13:16] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[20:13:16] [Server thread/INFO]: Time elapsed: 3051 ms
[20:13:16] [Server thread/INFO]: [WorldGuard] (mine) TNT ignition is PERMITTED.
[20:13:16] [Server thread/INFO]: [WorldGuard] (mine) Lighters are PERMITTED.
[20:13:16] [Server thread/INFO]: [WorldGuard] (mine) Lava fire is PERMITTED.
[20:13:16] [Server thread/INFO]: [WorldGuard] (mine) Fire spread is UNRESTRICTED.
[20:13:16] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'mine'
[20:13:16] [Server thread/INFO]: [Multiverse-Core] 2 - World(s) loaded.
[20:13:16] [Server thread/WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled!
[20:13:16] [Server thread/INFO]: [Multiverse-Core] Version 4.2.2-b812 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
[20:13:16] [Server thread/INFO]: [BedWars] Enabling BedWars v0.2.17
[20:13:16] [Server thread/INFO]: [BedWars] Successfully loaded messages for BedWars! Language: Russian
[20:13:16] [Server thread/INFO]: [BedWars] Loading statistics from database ...
[20:13:16] [Server thread/INFO]: [org.screamingsandals.bedwars.lib.HikariCP.hikari.HikariDataSource] HikariPool-1 - Starting...
[20:13:17] [Server thread/INFO]: [org.screamingsandals.bedwars.lib.HikariCP.hikari.HikariDataSource] HikariPool-1 - Start completed.
[20:13:17] [Server thread/WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
[20:13:17] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[20:13:17] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[20:13:17] [Server thread/WARN]: 	at com.mysql.cj.jdbc.result.ResultSetImpl.first(ResultSetImpl.java:603)
[20:13:17] [Server thread/WARN]: 	at org.screamingsandals.bedwars.lib.HikariCP.hikari.pool.HikariProxyResultSet.first(HikariProxyResultSet.java)
[20:13:17] [Server thread/WARN]: 	at org.screamingsandals.bedwars.statistics.PlayerStatisticManager.initializeLeaderboard(PlayerStatisticManager.java:87)
[20:13:17] [Server thread/WARN]: 	at org.screamingsandals.bedwars.statistics.PlayerStatisticManager.initialize(PlayerStatisticManager.java:53)
[20:13:17] [Server thread/WARN]: 	at org.screamingsandals.bedwars.Main.onEnable(Main.java:380)
[20:13:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:13:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[20:13:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[20:13:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[20:13:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[20:13:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[20:13:17] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
[20:13:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[20:13:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[20:13:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[20:13:17] [Server thread/INFO]: =====================  by ScreamingSandals <Misat11, Iamceph, Pronze>
[20:13:17] [Server thread/INFO]: + Screaming BedWars +  Version: 0.2.17 FREE
[20:13:17] [Server thread/INFO]: =====================  STABLE VERSION
[20:13:17] [Server thread/INFO]: [BW] Arena Mine loaded!
[20:13:17] [Server thread/INFO]: Everything is loaded! If you like our work, consider visiting our Patreon! <3
[20:13:17] [Server thread/INFO]: https://www.patreon.com/screamingsandals
[20:13:17] [Server thread/INFO]: [SecuredNetwork] Enabling SecuredNetwork v3.1
[20:13:17] [Server thread/INFO]: [SecuredNetwork] Thank you for downloading SecuredNetwork!
[20:13:17] [Server thread/INFO]: Running delayed init tasks
[20:13:17] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.17 (755)
[20:13:17] [Server thread/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[20:13:17] [Server thread/INFO]: Done (13.943s)! For help, type "help"
[20:13:17] [Server thread/INFO]: Timings Reset

#### Configuration (of config.yml and shop.yml)

###config.yml

locale: custom
debug: false
allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: true
join-randomly-after-lobby-timeout: false
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: true
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: false
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: false
player-respawn-items: false
gived-game-start-items: []
gived-player-respawn-items: []
disable-hunger: false
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
destroy-placed-blocks-by-explosion-except: []
destroy-placed-blocks-by-explosion: true
holo-above-bed: true
allow-spectator-join: false
disable-server-message:
  player-join: false
  player-leave: false
disable-flight: true
respawn-cooldown:
  enabled: true
  time: 5
stop-team-spawners-on-die: false
allow-fake-death: false
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
  enabled: true
  serverRestart: false
  serverStop: false
  server: bedwars-lobby
  auto-game-connect: true
  kick-when-proxy-too-slow: true
  motd:
    enabled: false
    waiting: '%name%: Waiting for players [%current%/%max%]'
    waiting_full: '%name%: Game is full [%current%/%max%]'
    running: '%name%: Game is running [%current%/%max%]'
    rebuilding: '%name%: Rebuilding...'
    disabled: '%name%: Game is disabled'
farmBlocks:
  enable: false
  blocks: []
scoreboard:
  enable: true
  title: §a%game%§r - %time%
  bedLost: §c✘
  anchorEmpty: §e✘
  bedExists: §a✔
  teamTitle: '%bed%%color%%team%'
title:
  enabled: true
  fadeIn: 0
  stay: 20
  fadeOut: 0
shop:
  rows: 4
  render-actual-rows: 6
  render-offset: 9
  render-header-start: 0
  render-footer-start: 45
  items-on-row: 9
  show-page-numbers: true
  inventory-type: CHEST
  citizens-enabled: false
items:
  jointeam: COMPASS
  leavegame: SLIME_BALL
  startgame: DIAMOND
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
  team-select: WHITE_WOOL
vault:
  enable: true
  reward:
    kill: 5
    win: 20
    final-kill: 5
    bed-destroy: 0
resources:
  gold:
    material: GOLD_INGOT
    color: GOLD
    name: Золото
    interval: 20
    translate: resource_gold
    spread: 1.0
  iron:
    material: IRON_INGOT
    color: GRAY
    name: Железо
    interval: 10
    translate: resource_iron
    spread: 1.0
  bronze:
    material: COPPER_INGOT
    color: DARK_RED
    name: Медь
    interval: 1
    translate: resource_bronze
    spread: 1.0
respawn:
  protection-enabled: true
  protection-time: 2
specials:
  action-bar-messages: true
  rescue-platform:
    is-breakable: false
    delay: 0
    break-time: 10
    distance: 1
    material: GLASS
  protection-wall:
    is-breakable: false
    delay: 20
    break-time: 0
    width: 5
    height: 3
    distance: 2
    material: CUT_SANDSTONE
  tnt-sheep:
    speed: 0.25
    follow-range: 10.0
    max-target-distance: 32
    explosion-time: 8
  arrow-blocker:
    protection-time: 10
    delay: 5
  warp-powder:
    teleport-time: 6
    delay: 0
  magnet-shoes:
    probability: 75
  golem:
    speed: 0.25
    follow-range: 10
    health: 20
    name-format: '%teamcolor%%team% Golem'
    show-name: true
    delay: 0
    collidable: false
  teamchest:
    turn-all-enderchests-to-teamchests: true
  throwable-fireball:
    explosion: 3.0
    damage: 2.0
  auto-igniteable-tnt:
    explosion-time: 8
    damage-placer: true
sounds:
  bed_destroyed:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1
    pitch: 1
  my_bed_destroyed:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1
    pitch: 1
  countdown:
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  game_start:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
  team_kill:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
  player_kill:
    sound: ENTITY_PLAYER_BIG_FALL
    volume: 1
    pitch: 1
  item_buy:
    sound: ENTITY_ITEM_PICKUP
    volume: 1
    pitch: 1
  upgrade_buy:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1
    pitch: 1
  respawn_cooldown_wait:
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  respawn_cooldown_done:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 1
game-effects:
  end:
    effects:
    - ==: Firework
      flicker: false
      trail: false
      colors:
      - &id001
        ==: Color
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id001
      type: BALL
    power: 1
    type: Firework
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
lobby-scoreboard:
  enabled: true
  title: §eБитва кроватей
  content:
  - ' '
  - '§fКарта: §2%arena%'
  - '§fИгроков: §2%players%§f/§2%maxplayers%'
  - ' '
  - §fОжидание ...
  - ' '
statistics:
  enabled: true
  type: database
  show-on-game-end: false
  bed-destroyed-kills: false
  scores:
    kill: 10
    final-kill: 0
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
database:
  host: 127.0.0.1
  port: 3306
  db: SomeDB
  user: SomeUser
  password: SomePassword
  table-prefix: bw_
  useSSL: false
bossbar:
  use-xp-bar: false
  lobby:
    enable: true
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: true
    color: GREEN
    style: SEGMENTED_20
holograms:
  enabled: true
  headline: Your §eBEDWARS§f stats
  leaderboard:
    headline: '&6Bedwars Leaderboard'
    format: '&l%order%. &7%name% - &a%score%'
    size: 10
chat:
  override: true
  format: '<%teamcolor%%name%§r> '
  separate-chat:
    lobby: false
    game: false
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '@a'
  team-chat-prefix: '@t'
  all-chat: '[ALL] '
  team-chat: '[TEAM] '
  death-chat: '[DEATH] '
  disable-all-chat-for-spectators: false
rewards:
  enabled: false
  player-win:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10
  player-final-kill:
  - /example {player} 10
lore:
  generate-automatically: true
  text:
  - '§7Стоймость:'
  - §7%price% %resource%
  - '§7Количество:'
  - §7%amount%
sign:
  lines:
  - §c§l[BedWars]
  - '%arena%'
  - '%status%'
  - '%players%'
  block-behind:
    enabled: false
    waiting: ORANGE_STAINED_GLASS
    rebuilding: BROWN_STAINED_GLASS
    in-game: GREEN_STAINED_GLASS
    game-disabled: RED_STAINED_GLASS
hotbar:
  selector: 0
  color: 1
  start: 2
  leave: 8
breakable:
  enabled: false
  asblacklist: false
  blocks: []
leaveshortcuts:
  enabled: false
  list:
  - leave
mainlobby:
  enabled: false
  location: ''
  world: ''
turnOnExperimentalGroovyShop: false
preventSpectatorFlyingAway: false
removePurchaseMessages: false
disableCakeEating: true
disableDragonEggTeleport: true
preventArenaFromGriefing: false
update-checker:
  zero:
    console: true
    admins: true
  one:
    console: true
    admins: true
target-block:
  allow-destroying-with-explosions: false
  respawn-anchor:
    fill-on-start: true
    enable-decrease: true
    sound:
      charge: BLOCK_RESPAWN_ANCHOR_CHARGE
      used: BLOCK_GLASS_BREAK
      deplete: BLOCK_RESPAWN_ANCHOR_DEPLETE
  cake:
    destroy-by-eating: true
event-hacks:
  damage: false
  destroy: false
  place: false
tab:
  enable: false
  header:
    enabled: true
    contents:
    - '&aMy awesome BedWars server'
    - '&bMap: %map%'
    - '&cPlayers: %respawnable%/%max%'
  footer:
    enabled: true
    contents:
    - '&eexample.com'
    - '&fWow!!'
    - §a%spectators% are watching this match
  hide-spectators: true
  hide-foreign-players: false
default-permissions:
  join: true
  leave: true
  stats: true
  list: true
  rejoin: true
  autojoin: true
  leaderboard: true
version: 2

###shop.yml
data:
#-   stack:
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

- stack: "DIAMOND_CHESTPLATE;1;Броня"
  items:
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_HELMET
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_LEGGINGS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of bronze
     properties: "applycolorbyteam"
     stack:
      type: LEATHER_BOOTS
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 1 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 1
   - price: 3 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
   - price: 7 of iron
     stack:
      type: CHAINMAIL_CHESTPLATE
      enchants:
       PROTECTION_ENVIRONMENTAL: 3
   - price: 10 of gold
     stack:
      type: IRON_HELMET
      display-name: Helm
      enchants:
       PROTECTION_ENVIRONMENTAL: 2
       
- stack: "DIAMOND_SWORD;1;Мечи"
  column: center
  items:
   - price: 8 of bronze
     stack:
      type: STICK
      enchants:
       KNOCKBACK: 1
   - price: 1 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 1
   - price: 3 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 2
   - price: 7 of iron
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 3
   - price: 3 of gold
     stack:
      type: GOLDEN_SWORD
      enchants:
       DAMAGE_ALL: 2
       KNOCKBACK: 1
   - price: 15 of gold
     stack:
      type: GOLDEN_AXE
      display-name: "Axe of Infinity"
      enchants:
       DAMAGE_ALL: 1
       DURABILITY: 1
       KNOCKBACK: 1
       
- stack: "BOW;1;Луки"
  column: right
  items:
   - price: 3 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
   - price: 7 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_DAMAGE: 1
   - price: 13 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_DAMAGE: 2
   - price: 14 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_FIRE: 1
   - price: 15 of gold
     stack:
      type: BOW
      enchants:
       ARROW_INFINITE: 1
       ARROW_FIRE: 1
       ARROW_KNOCKBACK: 1
   - ARROW for 1 of gold

- stack: "COOKED_PORKCHOP;1;Еда"
  row: 3
  column: 2
  items:
   - COOKED_PORKCHOP;2 for 4 of bronze
   - GOLDEN_APPLE for 2 of iron
   - BREAD;10 for 5 of gold

- stack:
   type: POTION
   meta:
    ==: ItemMeta
    meta-type: POTION
    display-name: "Зелья"
    potion-type: strength
  row: 3
  column: 6
  items:
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: healing
     price: 3 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strong_healing
     price: 5 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: swiftness
     price: 7 of iron
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: strength
     price: 1 of gold
   - stack:
      type: POTION
      meta:
       ==: ItemMeta
       meta-type: POTION
       potion-type: regeneration
     price: 3 of gold

- stack: "SANDSTONE;1;Блоки"
  linebreak: before
  items:
   - CUT_SANDSTONE;2 for 1 of bronze
   - END_STONE;3 for 7 of bronze
   - IRON_BLOCK for 3 of iron
   - GLOWSTONE;4 for 15 of bronze
   - price: 4 of bronze
     properties: "applycolorbyteam"
     stack: GLASS

- stack: "TNT;1;Приспособления"
  column: center
  items:
   - CHEST for 1 of iron
   - ENDER_CHEST for 1 of gold
   - price: 3 of iron
     stack: "TNT;1;Autoigniteable TNT"
     properties:
      - name: "AutoIgniteableTnt"
        explosion-time: 5
        damage-placer: false
   - price: 7 of iron
     properties:
      - name: "WarpPowder"
        delay: 6
     stack:
      type: GUNPOWDER
      display-name: "Warp Powder"
      lore:
       - "When using this powder you'll get"
       - "teleported to you spawn point within 6 seconds"
       - "Warning: Any movement will stop the process"
   - price: 3 of iron
     properties:
      - name: "Trap"
        data:
         - sound: ENTITY_SHEEP_AMBIENT
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
         - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
     stack:
      type: STRING
      display-name: "Trap"
      lore:
       - "Get informed if an enemy steps on your trap"
       - "and your enemy won't be able to move properly."
   - price: 6 of iron
     properties:
      - name: "MagnetShoes"
        probability: 75
     stack:
      type: IRON_BOOTS
      display-name: "Magnet-Shoes"
      lore:
       - "Wear those shoes and have a 75%"
       - "chance of getting no knockback!"
   - price: 5 of iron
     properties: "Tracker"
     stack:
      type: COMPASS
      display-name: "Tracker"
      lore:
       - "Wanna know where your closest target is?"
       - "Let's try this out!"
   - price: 15 of iron
     properties:
      - name: "rescueplatform"
        delay: 5
     stack:
      type: BLAZE_ROD
      display-name: "Rescue Platform"
      lore:
       - "Protect yourself from falling into"
       - "void with a Rescue Platform."
       - "This is your last hope!"
   - price: 5 of gold
     properties:
      - name: "arrowblocker"
        delay: 5
     stack:
      type: ENDER_EYE
      display-name: "Arrow Blocker"
      lore:
       - "Block arrows that are coming"
       - "for you with black magic."
       - "I mean, with this item."
   - price: 64 of bronze
     properties:
      - name: "protectionwall"
     stack:
      type: BRICKS
      display-name: "Protection Wall"
      lore:
       - "Instantly builds a wall that"
       - "can save your life!"
   - price: 24 of iron
     properties:
      - name: "Golem"
        speed: 0.25
        follow: 16.0
     stack:
      type: GHAST_SPAWN_EGG
      display-name: "Golem"
      lore:
       - "An iron golem that will protect"
       - "your team from the enemies."
   - price: 10 of gold
     properties: "TNTSheep"
     stack:
      type: SHEEP_SPAWN_EGG
      display-name: "TNT Sheep"
      lore:
       - "Use the TNT-Sheep! It will"
       - "walk towards your closest enemy"
       - "and explode within 8 seconds!"
   - price: 40 of iron
     properties: "ThrowableFireball"
     stack:
       type: FIRE_CHARGE
       display-name: "Fireball"
       lore:
         - "Is it a bird? Is it a plane?"
         - "By the time you know"
         - "you are dead!"

- stack: "DIAMOND_PICKAXE;1;Кирки"
  column: right
  items:
   - price: 4 of bronze
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 1
   - price: 2 of iron
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 2
   - price: 1 of gold
     stack:
      type: IRON_PICKAXE
      enchants:
       LOOT_BONUS_BLOCKS: 3

**Comment by iamceph** [comment]
Update to latest version.
