### ISSUE TITLE
Could not pass event PlayerInteractEvent to BedWars v0.2.17 

### ISSUE THREAD

**Issue by AlexTheKing14** [ScreamingSandals/BedWars#329]
Hello, I installed the plugin on my 1.17 server (with the SBA addon), I configured my map.

I start a game and when I have to choose a team with the compass, the server crashes with this error code:

`> [09:58:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BedWars v0.2.17
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:499) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:466) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:462) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1591) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1124) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1117) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1030) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
at net.minecraft.core.NonNullList.get(SourceFile:46) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.b(Container.java:272) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.d(Container.java:228) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.addSlotListener(Container.java:161) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.level.EntityPlayer.initMenu(EntityPlayer.java:545) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:325) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:303) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.screamingsandals.bedwars.lib.sgui.inventory.GuiHolder.<init>(GuiHolder.java:88) ~[?:?]
at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.openForPlayer(SimpleInventories.java:1010) ~[?:?]
at org.screamingsandals.bedwars.inventories.TeamSelectorInventory.openForPlayer(TeamSelectorInventory.java:68) ~[?:?]
at org.screamingsandals.bedwars.listener.PlayerListener.onPlayerInteract(PlayerListener.java:683) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:3100-Spigot-c9cea60-5182f92]
... 21 more
> [09:58:25] [Server thread/FATAL]: Error executing task on Server
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
at java.util.ArrayList.set(ArrayList.java:441) ~[?:?]
at net.minecraft.core.NonNullList.set(SourceFile:53) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.updateInventory(Container.java:176) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.updateInventory(CraftPlayer.java:749) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1605) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1124) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1117) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1030) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at java.lang.Thread.run(Thread.java:831) [?:?]
> [09:58:25] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1309) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1199) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1026) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
at net.minecraft.core.NonNullList.get(SourceFile:46) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.b(Container.java:272) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.d(Container.java:228) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.level.EntityPlayer.tick(EntityPlayer.java:588) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:815) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.level.World.a(World.java:692) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.level.WorldServer.lambda$11(WorldServer.java:527) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:508) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1296) ~[server.jar:3100-Spigot-c9cea60-5182f92]
... 5 more
> [09:58:25] [Server thread/ERROR]: Cause of unexpected exception was
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
at net.minecraft.core.NonNullList.get(SourceFile:46) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.b(Container.java:272) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.d(Container.java:228) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.level.EntityPlayer.tick(EntityPlayer.java:588) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:815) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.level.World.a(World.java:692) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.level.WorldServer.lambda$11(WorldServer.java:527) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:508) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1296) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1199) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1026) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at java.lang.Thread.run(Thread.java:831) [?:?]
> [09:58:25] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2021-06-30_09.58.25-server.txt
> [09:58:25] [Server thread/INFO]: Stopping server
> [09:58:25] [Server thread/INFO]: [SBAHypixelify] Disabling SBAHypixelify v1.4.3
> [09:58:25] [Server thread/INFO]: [SBAHypixelify] Cancelling current tasks....
> [09:58:25] [Server thread/INFO]: [BedWars] Disabling BedWars v0.2.17
> [09:58:25] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: bedwars
> [09:58:25] [Server thread/ERROR]: Error occurred while disabling BedWars v0.2.17 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
at java.util.ArrayList.set(ArrayList.java:441) ~[?:?]
at net.minecraft.core.NonNullList.set(SourceFile:53) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.world.inventory.Container.updateInventory(Container.java:176) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.updateInventory(CraftPlayer.java:749) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.screamingsandals.bedwars.game.GamePlayer.invClean(GamePlayer.java:160) ~[?:?]
at org.screamingsandals.bedwars.game.GamePlayer.clean(GamePlayer.java:164) ~[?:?]
at org.screamingsandals.bedwars.game.GamePlayer.changeGame(GamePlayer.java:37) ~[?:?]
at org.screamingsandals.bedwars.game.Game.stop(Game.java:1255) ~[?:?]
at org.screamingsandals.bedwars.Main.onDisable(Main.java:578) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:493) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:429) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:893) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:731) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1070) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3100-Spigot-c9cea60-5182f92]
at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by Misat11** [comment]
SBA addon doesn't support minecraft 1.17 yet

**Comment by AlexTheKing14** [comment]
However, people have managed to get the plugin to work in 1.17

**Comment by Misat11** [comment]
Unless they use older version with ViaVersion plugin, you can't run SBA in 1.17 yet (however the ScreamingBedWars plugin itself works)

**Comment by AlexTheKing14** [comment]
When do you think 1.17 will be supported by the plugin?

**Comment by AlexTheKing14** [comment]
In fact, I just tested without the addon, but it still crashes

**Comment by Misat11** [comment]
well I looked closer to the error, first try to get newer build of spigot because you got very strange errors (don't download the spigot from getbukkit.org or similar website, use buildtools to build your spigot or download paper from official papermc website)

**Comment by AlexTheKing14** [comment]
It works with Paper, thank you
