### ISSUE TITLE
[ERROR]: Could not pass event ShopTransactionEvent to BedWars v0.2.17

### ISSUE THREAD

**Issue by rtsai** [ScreamingSandals/BedWars#331]
#### Server and plugin version

Spigot version: 1.16.5 (paper #776)
BedWars version: 0.2.17-11

#### Installed plugins on server (can be obtained by `/pl`)

```
> pl
[20:36:21 INFO]: Plugins (6): BedWars, Multiverse-Core, ProtocolSupport, SimplePortals, ViaVersion, WorldEdit
```

- BedWars-0.2.17-11
- Multiverse-Core 4.2.3-SNAPSHOT (#845)
- ProtocolSupport #619
- ViaVersion-4.0.0
- SimplePortals 1.6.5
- worldedit-bukkit-7.2.5-dist.jar

#### Console log

- [latest.log](https://github.com/ScreamingSandals/BedWars/files/6774103/latest.log)

```
[ERROR]: Could not pass event ShopTransactionEvent to BedWars v0.2.17
java.lang.NullPointerException: Cannot invoke "org.screamingsandals.bedwars.api.game.ItemSpawnerType.getStack(int)" because "type" is null
        at org.screamingsandals.bedwars.inventories.ShopInventory.handleBuy(ShopInventory.java:416) ~[?:?]                                
        at org.screamingsandals.bedwars.inventories.ShopInventory.onShopTransaction(ShopInventory.java:278) ~[?:?]                                         
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor130.execute(Unknown Source) ~[?:?]              
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-776]                 
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-776]             
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-776]             
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-776]              
        at org.screamingsandals.bedwars.lib.sgui.listeners.InventoryListener.onInventoryClick(InventoryListener.java:172) ~[?:?]   
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source) ~[?:?]              
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-776]               
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-776]     
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-776]                 
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-776]                   
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-776]                                
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-776]                     
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-776]                     
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-776]                                                   
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-776]    
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-776]            
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-776]                      
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-776] 
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-776]             
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-776]         
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

#### Configuration (of config.yml and shop.yml)

- [config.yml.txt](https://github.com/ScreamingSandals/BedWars/files/6774105/config.yml.txt)
- [shop.yml.txt](https://github.com/ScreamingSandals/BedWars/files/6774106/shop.yml.txt)

**Comment by iamceph** [comment]
Update to latest version.
