### ISSUE TITLE
[ERROR] Could not pass event PlayerDeathEvent to BedWars v0.2.17

### ISSUE THREAD

**Issue by rtsai** [ScreamingSandals/BedWars#332]
#### Server and plugin version

Spigot version: 1.16.5 (paper #776)
BedWars version: 0.2.17-11

#### Installed plugins on server (can be obtained by `/pl`)

```
> pl
[20:36:21 INFO]: Plugins (6): BedWars, Multiverse-Core, ProtocolSupport, SimplePortals, ViaVersion, WorldEdit
```

- BedWars-0.2.17-11
- Multiverse-Core 4.2.3-SNAPSHOT (#845)
- ProtocolSupport #619
- ViaVersion-4.0.0
- SimplePortals 1.6.5
- worldedit-bukkit-7.2.5-dist.jar

#### Console log

- [latest.log](https://github.com/ScreamingSandals/BedWars/files/6774103/latest.log)

```
[20:20:42 ERROR]: Could not pass event PlayerDeathEvent to BedWars v0.2.17                                                            
java.lang.NullPointerException: Cannot read field "teamInfo" because "killerTeam" is null                                         
        at org.screamingsandals.bedwars.listener.PlayerListener.onPlayerDeath(PlayerListener.java:78) ~[?:?]                          
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source) ~[?:?]     
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-776]              
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-776]               
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-776]           
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-776]    
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:876) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:818) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:870) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:982) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.damage(CraftLivingEntity.java:347) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.damage(CraftLivingEntity.java:334) ~[patched_1.16.5.jar:git-Paper-776]
        at org.screamingsandals.bedwars.special.listener.MagnetShoesListener.onDamage(MagnetShoesListener.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor99.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-776]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:257) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1091) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1073) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:934) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1123) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1932) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:953) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1260) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:870) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:982) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.damage(CraftLivingEntity.java:347) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.damage(CraftLivingEntity.java:334) ~[patched_1.16.5.jar:git-Paper-776]
        at org.screamingsandals.bedwars.special.listener.MagnetShoesListener.onDamage(MagnetShoesListener.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor99.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-776]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:257) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:982) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:934) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1123) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1932) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:953) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1260) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:870) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:982) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityLiving.an(EntityLiving.java:2110) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.Entity.doVoidDamage(Entity.java:696) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.Entity.performVoidDamage(Entity.java:691) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.Entity.entityBaseTick(Entity.java:592) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:360) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:529) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2543) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:258) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:658) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:325) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1515) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-776]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

#### Configuration (of config.yml and shop.yml)

- [config.yml.txt](https://github.com/ScreamingSandals/BedWars/files/6774105/config.yml.txt)
- [shop.yml.txt](https://github.com/ScreamingSandals/BedWars/files/6774106/shop.yml.txt)

**Comment by iamceph** [comment]
Update to latest version please.
