### ISSUE TITLE
Console says something. 

### ISSUE THREAD

**Issue by Aadi-mone** [ScreamingSandals/BedWars#355]
#### Describe the bug
Something Keeps spamming in my console:

`[02:43:33 ERROR]: Could not pass event ShopTransactionEvent to BedWars v0.2.18
java.lang.NullPointerException: Cannot invoke "org.screamingsandals.bedwars.api.game.ItemSpawnerType.getStack(int)" because "type" is null
	at org.screamingsandals.bedwars.inventories.ShopInventory.handleBuy(ShopInventory.java:416) ~[?:?]
	at org.screamingsandals.bedwars.inventories.ShopInventory.onShopTransaction(ShopInventory.java:278) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor742.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[minecraft_server.jar:git-Paper-788]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[minecraft_server.jar:git-Paper-788]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Paper-788]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[minecraft_server.jar:git-Paper-788]
	at org.screamingsandals.bedwars.lib.sgui.listeners.InventoryListener.onInventoryClick(InventoryListener.java:172) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor688.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[minecraft_server.jar:git-Paper-788]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[minecraft_server.jar:git-Paper-788]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Paper-788]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1333) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[minecraft_server.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[minecraft_server.jar:git-Paper-788]
	at java.lang.Thread.run(Thread.java:831) [?:?]`
#### Server and plugin version
Spigot version:
BedWars version:

Latest Version

**Comment by zlataovce** [comment]
mismatched shop and config materials, reset your resources configuration and the shop.yml file. issue template not filled out completely.
