### ISSUE TITLE
Set Bed

### ISSUE THREAD

**Issue by MCJiaoLong** [ScreamingSandals/BedWars#358]
Set bed time with command
[14:34:59] [Server thread/WARN]: java.lang.NullPointerException
[14:34:59] [Server thread/WARN]:        at org.screamingsandals.bedwars.lib.bukkit.entity.BukkitEntityLiving.getTargetBlock(BukkitEntityLiving.java:63)
[14:34:59] [Server thread/WARN]:        at org.screamingsandals.bedwars.commands.admin.TeamCommand.lambda$construct$11(TeamCommand.java:221)
[14:34:59] [Server thread/WARN]:        at org.screamingsandals.bedwars.commands.admin.BaseAdminSubCommand.editMode(BaseAdminSubCommand.java:37)
[14:34:59] [Server thread/WARN]:        at org.screamingsandals.bedwars.commands.admin.TeamCommand.lambda$construct$12(TeamCommand.java:218)
[14:34:59] [Server thread/WARN]:        at org.screamingsandals.bedwars.lib.ext.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121)
[14:34:59] [Server thread/WARN]:        at org.screamingsandals.bedwars.lib.ext.cloud.CommandManager.executeCommand(CommandManager.java:176)
[14:34:59] [Server thread/WARN]:        at org.screamingsandals.bedwars.lib.ext.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:107)
[14:34:59] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:34:59] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:763)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1788)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1631)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1584)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851)
[14:34:59] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[14:34:59] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

server:
spigot-1.16.5
BedWars-0.3.0-SNAPSHOT-829.jar

**Comment by zlataovce** [comment]
0.3.0 is in development, use the stable versions.
