### ISSUE TITLE
Disconnects all players upon starting bedwars game

### ISSUE THREAD

**Issue by herferet** [ScreamingSandals/BedWars#363]
My first time trying to setup bedwars on my own server. Running a 1.17.1 paper server. When I start a bedwars game all players get the "disconnected" message and when they connect back, the game is no longer in progress.

Here's what appears in the console in yelllow:

[18:59:41 WARN]: java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)
[18:59:41 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[18:59:41 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2238)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.updateEntities(Hologram.java:231)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.updateEntities(Hologram.java:172)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.destroy(Hologram.java:145)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.Game.rebuild(Game.java:2240)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.Game.internalLeavePlayer(Game.java:832)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.GamePlayer.changeGame(GamePlayer.java:34)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.listener.PlayerListener.onPlayerQuit(PlayerListener.java:229)
[18:59:41 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source)
[18:59:41 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[18:59:41 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:59:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:59:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[18:59:41 WARN]:        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:607)
[18:59:41 WARN]:        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:592)
[18:59:41 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:1962)
[18:59:41 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1942)
[18:59:41 WARN]:        at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:741)
[18:59:41 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:221)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1648)
[18:59:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:59:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[18:59:41 WARN]: java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)
[18:59:41 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[18:59:41 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2238)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.updateEntities(Hologram.java:231)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.updateEntities(Hologram.java:172)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.destroy(Hologram.java:145)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.Game.rebuild(Game.java:2240)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.Game.internalLeavePlayer(Game.java:832)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.GamePlayer.changeGame(GamePlayer.java:34)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.listener.PlayerListener.onPlayerQuit(PlayerListener.java:229)
[18:59:41 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source)
[18:59:41 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[18:59:41 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:59:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:59:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[18:59:41 WARN]:        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:607)
[18:59:41 WARN]:        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:592)
[18:59:41 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:1962)
[18:59:41 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1942)
[18:59:41 WARN]:        at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:741)
[18:59:41 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:221)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1648)
[18:59:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:59:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[18:59:41 WARN]: java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)
[18:59:41 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[18:59:41 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2238)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.updateEntities(Hologram.java:231)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.updateEntities(Hologram.java:172)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.destroy(Hologram.java:145)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.Game.rebuild(Game.java:2240)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.Game.internalLeavePlayer(Game.java:832)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.GamePlayer.changeGame(GamePlayer.java:34)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.listener.PlayerListener.onPlayerQuit(PlayerListener.java:229)
[18:59:41 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source)
[18:59:41 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[18:59:41 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:59:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:59:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[18:59:41 WARN]:        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:607)
[18:59:41 WARN]:        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:592)
[18:59:41 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:1962)
[18:59:41 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1942)
[18:59:41 WARN]:        at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:741)
[18:59:41 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:221)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1648)
[18:59:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:59:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[18:59:41 WARN]: java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)
[18:59:41 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[18:59:41 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2238)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.updateEntities(Hologram.java:231)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.updateEntities(Hologram.java:172)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.destroy(Hologram.java:145)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.Game.rebuild(Game.java:2240)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.Game.internalLeavePlayer(Game.java:832)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.game.GamePlayer.changeGame(GamePlayer.java:34)
[18:59:41 WARN]:        at BedWars-0.2.18-14.jar//org.screamingsandals.bedwars.listener.PlayerListener.onPlayerQuit(PlayerListener.java:229)
[18:59:41 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source)
[18:59:41 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[18:59:41 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:59:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:59:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[18:59:41 WARN]:        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:607)
[18:59:41 WARN]:        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:592)
[18:59:41 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:1962)
[18:59:41 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1942)
[18:59:41 WARN]:        at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:741)
[18:59:41 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:221)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1648)
[18:59:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[18:59:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:59:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[18:59:41 INFO]: Gabija789 left the game
[18:59:41 WARN]: java.lang.UnsupportedOperationException: Cannot send packet to offline player!
[18:59:41 WARN]:        at SBA-1.5.5.jar//io.github.pronze.lib.screaminglib.bukkit.packet.BukkitSPacket.sendPacket(BukkitSPacket.java:42)
[18:59:41 WARN]:        at SBA-1.5.5.jar//io.github.pronze.lib.screaminglib.bukkit.hologram.BukkitHologram.lambda$update$5(BukkitHologram.java:164)
[18:59:41 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[18:59:41 WARN]:        at SBA-1.5.5.jar//io.github.pronze.lib.screaminglib.bukkit.hologram.BukkitHologram.update(BukkitHologram.java:164)
[18:59:41 WARN]:        at SBA-1.5.5.jar//io.github.pronze.lib.screaminglib.bukkit.hologram.BukkitHologram.onViewerAdded(BukkitHologram.java:62)
[18:59:41 WARN]:        at SBA-1.5.5.jar//io.github.pronze.lib.screaminglib.bukkit.hologram.BukkitHologramManager.lambda$onTeleport$8(BukkitHologramManager.java:235)
[18:59:41 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:59:41 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:59:41 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:59:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[18:59:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[18:59:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[18:59:41 WARN]: java.lang.UnsupportedOperationException: Cannot send packet to offline player!
[18:59:41 WARN]:        at SBA-1.5.5.jar//io.github.pronze.lib.screaminglib.bukkit.packet.BukkitSPacket.sendPacket(BukkitSPacket.java:42)
[18:59:41 WARN]:        at SBA-1.5.5.jar//io.github.pronze.lib.screaminglib.bukkit.hologram.BukkitHologram.lambda$update$5(BukkitHologram.java:164)
[18:59:41 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[18:59:41 WARN]:        at SBA-1.5.5.jar//io.github.pronze.lib.screaminglib.bukkit.hologram.BukkitHologram.update(BukkitHologram.java:164)
[18:59:41 WARN]:        at SBA-1.5.5.jar//io.github.pronze.lib.screaminglib.bukkit.hologram.BukkitHologram.onViewerAdded(BukkitHologram.java:62)
[18:59:41 WARN]:        at SBA-1.5.5.jar//io.github.pronze.lib.screaminglib.bukkit.hologram.BukkitHologramManager.lambda$onTeleport$8(BukkitHologramManager.java:235)
[18:59:41 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:59:41 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:59:41 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:59:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[18:59:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[18:59:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by zlataovce** [comment]
sba is not compatible with 1.17.1 at all, you will have to downgrade your minecraft version if you want to use it

**Comment by herferet** [comment]
I thought of downgrading the paper serer to 1.17 but I can't find where I can download this older version
