### ISSUE TITLE
Plugin returns error message if players try to use /bw join during an ongoing game.

### ISSUE THREAD

**Issue by captainion2119** [ScreamingSandals/BedWars#384]
Description:
When a game is on-going, and another player in the lobby(Main server lobby using Multiverse Core plugin, not BedWars arena lobby) uses /bw join, the plugin returns "An internal error occurred while attempting to perform this command"

Server and plugin information
Paper version: paper-1.17.1-353
BedWars version: BedWars-0.2.20-36

Installed plugins on server:
BedWars, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, Multiverse-Core, Vault, Votifier, VotingPlugin

Console log:
[20:46:31] [Server thread/INFO]: updownvizzii issued server command: /bw join
[20:46:31] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BedWars v0.2.20
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-353]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-353]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-353]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
    at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
    at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-353]
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423) ~[patched_1.17.1.jar:git-Paper-353]
    at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-353]
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1401) ~[patched_1.17.1.jar:git-Paper-353]
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1394) ~[patched_1.17.1.jar:git-Paper-353]
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1372) ~[patched_1.17.1.jar:git-Paper-353]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Paper-353]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-353]
    at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map$Entry.getValue()" because "lastEntry" is null
    at org.screamingsandals.bedwars.Main.getGameWithHighestPlayers(Main.java:638) ~[BedWars-0.2.20-36.jar:?]
    at org.screamingsandals.bedwars.commands.JoinCommand.execute(JoinCommand.java:33) ~[BedWars-0.2.20-36.jar:?]
    at org.screamingsandals.bedwars.commands.BwCommandsExecutor.onCommand(BwCommandsExecutor.java:72) ~[BedWars-0.2.20-36.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-353]
    ... 21 more

NOTE: (21 lines truncated.)

Configuration (of config.yml and shop.yml):
(provided in the attachment.)

[config (4).txt](https://github.com/ScreamingSandals/BedWars/files/7492531/config.4.txt)
[shop.txt](https://github.com/ScreamingSandals/BedWars/files/7492530/shop.txt)

**Comment by captainion2119** [comment]
... no responses?

we are on a short time frame as of now, because we are planning on releasing a beta launch of our MC network

:D

**Comment by zlataovce** [comment]
does this happen only when all arenas are full?

**Comment by zlataovce** [comment]
try [this](https://ci.screamingsandals.org/job/BedWars-0.2.x/40/artifact/plugin/build/libs/BedWars-0.2.21-SNAPSHOT-40.jar) build and let us know if that fixed the issue

**Comment by captainion2119** [comment]
> try [this](https://ci.screamingsandals.org/job/BedWars-0.2.x/40/artifact/plugin/build/libs/BedWars-0.2.21-SNAPSHOT-40.jar) build and let us know if that fixed the issue

Yes that fixed the issue, thank you for your time!
