### ISSUE TITLE
/bw addholo stats does Not Work

### ISSUE THREAD

**Issue by KittenPixel-cell** [ScreamingSandals/BedWars#389]
#### Server and plugin version
Paper version: 1.15.2
BedWars version: BedWars-0.2.21

#### Installed plugins on server (can be obtained by `/pl`)
Yes

#### Console log
[14:47:34 INFO]: KittenPixel issued server command: /bw addholo stats
[14:47:34 WARN]: Task #36388 for BedWars v0.2.20 generated an exception
java.lang.NullPointerException: null
	at org.screamingsandals.bedwars.holograms.StatisticsHolograms.updatePlayerHologram(StatisticsHolograms.java:111) ~[?:?]
	at org.screamingsandals.bedwars.holograms.StatisticsHolograms.lambda$updateHolograms$2(StatisticsHolograms.java:86) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1265) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by Misat11** [comment]
This issue is invalid and we forgot to close it. If you still have this problem, please create a new issue and follow the issue template properly.
