### ISSUE TITLE
Plugin not loading Database

### ISSUE THREAD

**Issue by amazonal3xa** [ScreamingSandals/BedWars#399]
#### Describe the bug
When filling in database config, the plugin will not load

Error: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=....

#### Server and plugin version
Spigot version: 1.12.2
BedWars version: 0.2.22

#### Installed plugins on server (can be obtained by `/pl`)

 Essentials, HolographicDisplays, LuckPerms, NoCheatPlus, PlaceholderAPI, Plan, ProtocolLib, Vault

#### Console log

```
[00:07:16 INFO]: [BedWars] Enabling BedWars v0.2.22
[00:07:16 INFO]: [BedWars] Successfully loaded messages for BedWars! Language: German
[00:07:16 INFO]: [BedWars] Loading statistics from database ...
[00:07:16 INFO]: [org.screamingsandals.bedwars.lib.HikariCP.hikari.HikariDataSource] HikariPool-1 - Starting...
[00:07:16 WARN]: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://172.18.0.1:3306/mcsql?autoReconnect=true&serverTimezone=Europe/Berlin&useSSL=false
[00:07:16 WARN]:        at org.screamingsandals.bedwars.lib.HikariCP.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.lib.HikariCP.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:320)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.lib.HikariCP.hikari.pool.PoolBase.<init>(PoolBase.java:109)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.lib.HikariCP.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.lib.HikariCP.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.database.DatabaseManager.initialize(DatabaseManager.java:40)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.statistics.PlayerStatisticManager.initializeDatabase(PlayerStatisticManager.java:60)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.statistics.PlayerStatisticManager.initialize(PlayerStatisticManager.java:47)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.Main.onEnable(Main.java:378)
[00:07:16 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:07:16 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[00:07:16 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:07:16 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[00:07:16 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[00:07:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[00:07:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[00:07:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[00:07:16 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[00:07:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[00:07:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[00:07:16 WARN]: Caused by: java.sql.SQLException: No suitable driver
[00:07:16 WARN]:        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.lib.HikariCP.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
[00:07:16 WARN]:        ... 19 more
[00:07:16 WARN]: java.lang.NullPointerException
[00:07:16 WARN]:        at org.screamingsandals.bedwars.database.DatabaseManager.getConnection(DatabaseManager.java:45)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.statistics.PlayerStatisticManager.initializeLeaderboard(PlayerStatisticManager.java:82)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.statistics.PlayerStatisticManager.initialize(PlayerStatisticManager.java:53)
[00:07:16 WARN]:        at org.screamingsandals.bedwars.Main.onEnable(Main.java:378)
[00:07:16 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:07:16 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[00:07:16 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:07:16 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[00:07:16 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[00:07:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[00:07:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[00:07:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[00:07:16 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[00:07:16 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[00:07:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[00:07:16 INFO]: [PlaceholderAPI] Successfully registered expansion: bedwars [0.2.22]
[00:07:16 INFO]: =====================  by ScreamingSandals <Misat11, Iamceph, Pronze>
[00:07:16 INFO]: + Screaming BedWars +  Version: 0.2.22 FREE
[00:07:16 INFO]: =====================  STABLE VERSION
[00:07:16 INFO]: [BW] Found Vault
[00:07:16 INFO]: [BW] Arena China loaded!
[00:07:16 INFO]: Everything is loaded! If you like our work, consider visiting our Patreon! <3
[00:07:16 INFO]: https://www.patreon.com/screamingsandals
```

#### Configuration (of config.yml and shop.yml) 

only config provided, rest unchanged

```YAML
statistics:
  enabled: true
  type: database
  show-on-game-end: true
  bed-destroyed-kills: false
  scores:
    kill: 10
    final-kill: 0
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
database:
  host: 172.18.0.1
  port: 3306
  db: 'mcsql'
  user: 'mcsql'
  password: ''
  table-prefix: bw_
  useSSL: false
```

**Comment by Misat11** [comment]
This is weird because the shared mysql driver should be present in the spigot 1.12.2 server. What server software are you using? Also you shouldn't send us your passwords.

**Comment by amazonal3xa** [comment]
The server is running regular paper 1.12.2. Don’t worry about the password, that’s a random string on a user which is not public exposed anyway. Still thank u for your awareness.

**Comment by amazonal3xa** [comment]
We also tested regular spigot, version 1.12.2. Same error.

**Comment by YannickGTHD** [comment]
Are there any updates about this problem? 
For your Information: Our Server is hosted in a Pterodactyl panel in a docker container. Could be helpful to track down the problem.

**Comment by Misat11** [comment]
Both Spigot and Paper contain suitable driver for mysql. You probably have some third party server jar or some other plugin somehow unregisters the mysql driver.

**Comment by amazonal3xa** [comment]
We found the problem. With Java 8 everything works fine. Shouldn't it be compatible with java 11, since the plugin is running on 1.13 natively?

**Comment by Misat11** [comment]
The plugin works fine on java 11 as well. The problem is probably with the database connector bundled in the server jar, you should consider updating to newer minecraft version.
