### ISSUE TITLE
Unable to save map edits.

### ISSUE THREAD

**Issue by ignpoppyseed** [ScreamingSandals/BedWars#403]
#### Describe the bug
Cannot save edits my edits to the map. Chat states: "An internal error occurred while attempting to perform this command"

#### Server and plugin version
Spigot version: 1.19.4
BedWars version: 0.2.18

#### Installed plugins on server (can be obtained by `/pl`)
![image](https://user-images.githubusercontent.com/87223326/150039350-b6eb650b-93ee-463f-b731-999c91501787.png)

#### Console log
[16:11:21 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BedWars v0.2.18
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.4.jar:git-Paper-775]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-775]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-775]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-775]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.screamingsandals.bedwars.game.ItemSpawnerType.getConfigKey()" because "spawner.type" is null
	at org.screamingsandals.bedwars.game.Game.saveToConfig(Game.java:1143) ~[?:?]
	at org.screamingsandals.bedwars.game.GameCreator.cmd(GameCreator.java:247) ~[?:?]
	at org.screamingsandals.bedwars.commands.AdminCommand.execute(AdminCommand.java:470) ~[?:?]
	at org.screamingsandals.bedwars.commands.BwCommandsExecutor.onCommand(BwCommandsExecutor.java:72) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.4.jar:git-Paper-775]
	... 15 more

**Comment by zlataovce** [comment]
corrupted configuration, remove it and let it generate from defaults

**Comment by ignpoppyseed** [comment]
> corrupted configuration, remove it and let it generate from defaults

thank you so much
