### ISSUE TITLE
Event failure console spam from plugin

### ISSUE THREAD

**Issue by maxer4192** [ScreamingSandals/BedWars#410]
I've got this server using this plugin which likes to periodically spam console. I feel like it's from a holograms plugin or something but I don't know how to resolve this issue. Java error dump below:

`[01:23:06 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "this.loc" is null
[01:23:06 WARN]:        at BedWars-0.2.23.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.update(Hologram.java:273)
[01:23:06 WARN]:        at BedWars-0.2.23.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.removeViewers(Hologram.java:126)
[01:23:06 WARN]:        at BedWars-0.2.23.jar//org.screamingsandals.bedwars.lib.nms.holograms.Hologram.removeViewer(Hologram.java:118)
[01:23:06 WARN]:        at BedWars-0.2.23.jar//org.screamingsandals.bedwars.lib.nms.holograms.HologramManager.onPlayersQuit(HologramManager.java:244)
[01:23:06 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor429.execute(Unknown Source)
[01:23:06 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[01:23:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[01:23:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:23:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[01:23:06 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:617)
[01:23:06 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:602)
[01:23:06 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:2000)
[01:23:06 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1980)
[01:23:06 WARN]:        at net.minecraft.network.NetworkManager.m(NetworkManager.java:755)
[01:23:06 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:221)
[01:23:06 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1624)
[01:23:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[01:23:06 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1458)
[01:23:06 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1227)
[01:23:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:23:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

Any thoughts on a fix for this?

**Comment by zlataovce** [comment]
follow the issue template

**Comment by zlataovce** [comment]
closing due to inactivity
