### ISSUE TITLE
can't destroy and place blocks in bedwar

### ISSUE THREAD

**Issue by shinefield** [ScreamingSandals/BedWars#412]
#### Describe the bug
After setting up the game
can't destroy and place blocks in bedwar game

#### Server and plugin version
Spigot version:1.12
BedWars version:0.2.22

#### Installed plugins on server (can be obtained by `/pl`)
[08:46:37] [Server thread/INFO] []: Plugins (18): Citizens, NoSpawnChunks, EnchantControl, Essentials, EssentialsProtect, LoginSecurity, GroupManager, BanItem, BreedingLimiter, EssentialsAntiBuild, EntitySearch, ChunksExplorerLimiter, NoFishRepair, RandomLocation, ProtocolLib, Multiverse-Core, Orebfuscator4, Shopkeepers

#### Console log
not log

#### Configuration (of config.yml and shop.yml)
default config

**Comment by zlataovce** [comment]
disable any anti build/anti griefing plugins on the bedwars world

**Comment by shinefield** [comment]
@zlataovce BedWar need to set permissions?

**Comment by zlataovce** [comment]
no, just remove/disable those plugins, BW protects the maps itself

**Comment by shinefield** [comment]
[15:01:17] [Server thread/INFO]: [BedWars] Enabling BedWars v0.2.22
[15:01:17] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 26, column 67:
     ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ...
                                         ^

[15:01:17] [Server thread/WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
[15:01:17] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162)
[15:01:17] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130)
[15:01:17] [Server thread/WARN]:        at org.screamingsandals.bedwars.lib.lang.BukkitTranslateContainer.<init>(BukkitTranslateContainer.java:56)
[15:01:17] [Server thread/WARN]:        at org.screamingsandals.bedwars.lib.lang.BukkitTranslateContainer.<init>(BukkitTranslateContainer.java:43)
[15:01:17] [Server thread/WARN]:        at org.screamingsandals.bedwars.lib.lang.I18nBukkit.load(I18nBukkit.java:23)
[15:01:17] [Server thread/WARN]:        at org.screamingsandals.bedwars.Main.onEnable(Main.java:369)
[15:01:17] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:01:17] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328)
[15:01:17] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:01:17] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:436)
[15:01:17] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384)
[15:01:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:387)
[15:01:17] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[15:01:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
[15:01:17] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[15:01:17] [Server thread/WARN]: Caused by: mapping values are not allowed here
 in 'string', line 26, column 67:
     ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ...
                                         ^

[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:872)
[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:249)
[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:252)
[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:167)
[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:124)
[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140)
[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
[15:01:17] [Server thread/WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
[15:01:17] [Server thread/WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
[15:01:17] [Server thread/WARN]:        ... 15 more
[15:01:17] [Server thread/INFO]: [BedWars] Successfully loaded messages for BedWars! Language: Simplified Chinese
[15:01:17] [Server thread/INFO]: [BedWars] Loading statistics from YAML-File ...
[15:01:20] [Server thread/INFO]: =====================  by ScreamingSandals <Misat11, Iamceph, Pronze>
[15:01:20] [Server thread/INFO]: + Screaming BedWars +  Version: 0.2.22 FREE
[15:01:20] [Server thread/INFO]: =====================  STABLE VERSION
[15:01:20] [Server thread/WARN]: [BedWars] Bedwars 0.3.0 will require at least Java 11. Your server is not prepared for it. Update your Java or contact your hosting.
[15:01:20] [Server thread/WARN]: [BedWars] https://docs.screamingsandals.org/Other/java11.html
[15:01:20] [Server thread/INFO]: [BW] Arena qczz loaded!
[15:01:20] [Server thread/INFO]: [BW] Arena qczz2 loaded!
[15:01:20] [Server thread/INFO]: Everything is loaded! If you like our work, consider visiting our Patreon! <3
[15:01:20] [Server thread/INFO]: https://www.patreon.com/screamingsandals
[15:01:20] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:01:20] [Server thread/INFO]: Done (14.225s)! For help, type "help" or "?"
[15:01:20] [Server thread/INFO]: Overridden 112 commands
[15:01:20] [Server thread/INFO]: [Citizens] Loaded 0 NPCs.
[15:01:20] [Server thread/INFO]: CoroUtil being reinitialized
[15:01:22] [Craft Scheduler Thread - 8/INFO]: [起床战争] New RELEASE version 0.2.23 of BedWars is available!
[15:01:22] [Craft Scheduler Thread - 8/INFO]: [起床战争] Download it from https://www.spigotmc.org/resources/63714/download?version=443671
>

**Comment by zlataovce** [comment]
invalid configuration, undo your changes or remove the configuration file to reset it completely

**Comment by shinefield** [comment]
Still no, thank you for your answer, it should be a problem with my server, I gave up. :>
@zlataovce
