### ISSUE TITLE
[Bug]: Upgrade Shop is not working 

### ISSUE THREAD

**Issue by Bhrol** [ScreamingSandals/BedWars#525]
### Bug description

Using the plugin in 1.20.4, when I launch the game in one team mode (using cheat mode) and buy an upgrade from the upgrade shop (using the certain-poupular-server/upgrade-shop.yml for example), it just give me the item of the shop and does not give the expected effect (no sharpness or protection).

### Console log

I tried to get the dump but instead had this : 

[02:00:03] [Thread-13/WARN]: java.lang.IllegalArgumentException: Configuration does not accept objects of type class java.util.stream.ReferencePipeline$3
[02:00:03] [Thread-13/WARN]: 	at BedWars-0.3.0-SNAPSHOT-dev.jar//org.screamingsandals.bedwars.lib.ext.configurate.ScalarConfigValue.set(ScalarConfigValue.java:45)
[02:00:03] [Thread-13/WARN]: 	at BedWars-0.3.0-SNAPSHOT-dev.jar//org.screamingsandals.bedwars.lib.ext.configurate.AbstractConfigurationNode.insertNewValue(AbstractConfigurationNode.java:264)
[02:00:03] [Thread-13/WARN]: 	at BedWars-0.3.0-SNAPSHOT-dev.jar//org.screamingsandals.bedwars.lib.ext.configurate.AbstractConfigurationNode.raw(AbstractConfigurationNode.java:340)
[02:00:03] [Thread-13/WARN]: 	at BedWars-0.3.0-SNAPSHOT-dev.jar//org.screamingsandals.bedwars.lib.ext.configurate.MapConfigValue.set(MapConfigValue.java:75)
[02:00:03] [Thread-13/WARN]: 	at BedWars-0.3.0-SNAPSHOT-dev.jar//org.screamingsandals.bedwars.lib.ext.configurate.AbstractConfigurationNode.insertNewValue(AbstractConfigurationNode.java:264)
[02:00:03] [Thread-13/WARN]: 	at BedWars-0.3.0-SNAPSHOT-dev.jar//org.screamingsandals.bedwars.lib.ext.configurate.AbstractConfigurationNode.set(AbstractConfigurationNode.java:177)
[02:00:03] [Thread-13/WARN]: 	at BedWars-0.3.0-SNAPSHOT-dev.jar//org.screamingsandals.bedwars.commands.DumpCommand.lambda$construct$15(DumpCommand.java:344)
[02:00:03] [Thread-13/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

### Additional information

The plugin I used is one I builded using your repo, but I really didn't change much so it has no impact on the part of the shop.

**Comment by Misat11** [comment]
Hello,

upgrades are not implemented yet in the development versions of 0.3.0. There is currently no ETA for this feature to be implemented.

Btw thank you for the discovery that /bw dump does not work :)

**Comment by Bhrol** [comment]
Thanks for your fast answer. 

Actually this morning I downgraded to v2.31 (just remodifying the line of codes I needed) , and the upgrade shop still don't work.

This time I've got the dump : https://paste.gg/79ef783a1fe94be2976fd23e977534d2

I also have an other question that has nothing to do with the problem : is there a way to publish a scoreboard of players and teams at the end of the game ?

**Comment by Misat11** [comment]
Current releases (0.2.x) do not have an upgrade shop at all, there's an addon called SBA which adds it. We have plans to merge this addon into the main plugin in 0.3.0, however it is not finished yet.

**Comment by matrixguy69** [comment]
hi im getting the same issue any solution
