### ISSUE TITLE
[Bug]: Rebuilding bed blocks on legacy versions can fail, resulting in never ending match

### ISSUE THREAD

**Issue by Chaostarts** [ScreamingSandals/BedWars#542]
### Bug description

Unable to exit the game after the match ends

### BedWars dump (can be obtained via `/bw dump`)

https://paste.gg/aff912cee87344efa87235fa4efd2a3f

### Console log

```
[16:48:57 WARN]: [BedWars] Task #3218 for BedWars v0.2.33.1 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.getId()" because "type" is null
        at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlockState.setType(CraftBlockState.java:106) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at org.screamingsandals.bedwars.region.LegacyRegion.regen(LegacyRegion.java:151) ~[?:?]
        at org.screamingsandals.bedwars.game.Game.rebuild(Game.java:2417) ~[?:?]
        at org.screamingsandals.bedwars.game.Game.run(Game.java:2365) ~[?:?]
        at org.screamingsandals.bedwars.game.Game$7.run(Game.java:2525) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
[16:48:58 WARN]: [BedWars] Task #3218 for BedWars v0.2.33.1 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.getId()" because "type" is null
        at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlockState.setType(CraftBlockState.java:106) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at org.screamingsandals.bedwars.region.LegacyRegion.regen(LegacyRegion.java:151) ~[?:?]
        at org.screamingsandals.bedwars.game.Game.rebuild(Game.java:2417) ~[?:?]
        at org.screamingsandals.bedwars.game.Game.run(Game.java:2365) ~[?:?]
        at org.screamingsandals.bedwars.game.Game$7.run(Game.java:2525) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by Misat11** [comment]
Can you try latest snapshot from https://github.com/ScreamingSandals/BedWars/actions/workflows/build-0-2-x.yml and check if you can still reproduce this issue?

**Comment by Chaostarts** [comment]
> Can you try latest snapshot from https://github.com/ScreamingSandals/BedWars/actions/workflows/build-0-2-x.yml and check if you can still reproduce this issue?

The problem has been solved, I have reset the bed of teams
