### ISSUE TITLE
[Bug]: Network Protocol Error

### ISSUE THREAD

**Issue by Sonnelus** [ScreamingSandals/BedWars#546]
### Bug description

Since 1.21, after you destroy the bed, you got disconnected with Network Protocol Error

### BedWars dump (can be obtained via `/bw dump`)

https://paste.gg/p/anonymous/2a3632755737404187561f34f2dc1271

### Console log

No console errors

### Additional information

PaperSpigot 1.21, build 130 - the newest one

**Comment by Misat11** [comment]
Tested on 1.21.1 build 5 (that version is protocol-compatible with 1.21) and I cannot reproduce your issue. Can you provide more details, like the network error report from your client?

**Comment by Sonnelus** [comment]
> Tested on 1.21.1 build 5 (that version is protocol-compatible with 1.21) and I cannot reproduce your issue. Can you provide more details, like the network error report from your client?

First this yellow text:
```
21:46:06.305
net.minecraft.class_634
Render thread
Received packet for unknown team a04: team action: REMOVE, player action: null
```

AND after being killed without bed, red text:

```
21:53:31.775
net.minecraft.class_8673
Render thread
Failed to handle packet net.minecraft.class_5900@5015744
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'Red'.
	at net.minecraft.class_269.method_1157(class_269.java:308)
	at net.minecraft.class_634.method_11099(class_634.java:2050)
	at net.minecraft.class_5900.method_34173(class_5900.java:132)
	at net.minecraft.class_5900.method_11054(class_5900.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Client disconnected with reason: Network Protocol Error

**Comment by Misat11** [comment]
From the errors you have sent it looks like a different plugin is clashing with BedWars when it comes to scoreboard teams. The first error refers to a team `a04`, you do not have such team in any of your arena, so that error does not come from BedWars. 

My guess was the link is connected to BetterTeams since they have the same problem reported on their issue tracker https://github.com/booksaw/BetterTeams/issues/618, yet I was unable to replicate this, so there is probably:
* some other plugin causing the issue (I personally cannot test all of the plugins listed),
* some specific configuration of those plugins,
* or a bug directly in Spigot/Paper, since SBW 0.2.x does not use packets directly, but utilizes Bukkit API.

**Comment by Sonnelus** [comment]
I had simillar problems with BetterTeams (disconnecting all players from server) since 1.21, but now, after i've changed config and disabled usage of minecraft:teams, it works fine.

I have simmilar problems with MurderMystery plugin (worse than BedWars: disconnecting during game, not on the end like BedWars).

So am I thinking right here: I should try to uninstall some other plugins one by one to check which one is clashing with Bedwars? Especially plugins using minecraft:teams, like minigames?
