### ISSUE TITLE
[Bug]: SBA stores is not working

### ISSUE THREAD

**Issue by PatrixMC** [ScreamingSandals/BedWars#557]
### Bug description

/bw admin (mapname) store add Store shop.yml false
/bw admin (mapname) store add TeamUpgrades upgradeShop.yml false
I write all these commands correctly. But while the game is in progress, the stores do not work

**Comment by PatrixMC** [comment]
Sorry The Dump isn't Dump

**Comment by PatrixMC** [comment]
[13:03:03 WARN]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[13:03:03 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1238)
[13:03:03 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1137)
[13:03:03 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1075)
[13:03:03 WARN]:        at BedWars-0.2.36.1.jar//org.screamingsandals.bedwars.commands.DumpCommand.lambda$execute$12(DumpCommand.java:357)
[13:03:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[13:03:03 WARN]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[13:03:03 WARN]:        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
[13:03:03 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:182)
[13:03:03 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144)
[13:03:03 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:1227)
[13:03:03 WARN]:        ... 4 more

Gdy pisze /bw dump to pokazuje Dump Failed mam tylko to z konsoli

**Comment by Misat11** [comment]
Paste.gg does not seem to work now, you would have to use pastes.dev:
`/bw dump pastes.dev`

This issue isn't rly relevant to SBW since you are talking about SBA shop. You have already opened an issue in the SBA repo, so continue in that issue https://github.com/boiscljo/SBA/issues/96

**Comment by PatrixMC** [comment]
https://pastes.dev/t6wTmyd6Rf
