### ISSUE TITLE
Villager Shop does not open.

### ISSUE THREAD

**Issue by tjd2** [ScreamingSandals/BedWars#67]
**Describe the bug**
I am not able to open villager shop, when in game. It throws error in console. Completely setting up everything from scratch didn't help.
Problem actually started most likely after updating PaperSpigot to latest version.

**Server and plugin version**
Spigot version: git-Paper-214
BedWars version: 0.2.1 (does the same on 0.2.0)

**Installed plugins on server (can be obtained by `/pl`):**
┬AsyncWorldEdit┬, ┬AuthMe┬, ┬BasicAntiCheat┬, ┬BedWars┬, ┬ChatControl┬, ┬ChestShop┬, ┬DeepVanish┬, ┬Duels┬, ┬Essentials┬, ┬EssentialsChat┬, ┬EssentialsSpawn┬, ┬ID-Library┬, ┬LuckPerms┬, ┬MineResetLite┬, ┬MobArena┬, ┬Multiverse-Core┬, ┬NerfPhantoms┬, ┬NoPlugins┬, ┬PluginConstructorAPI┬, ┬PluginManager┬, ┬ProtocolLib┬, ┬Residence┬, ┬RFChairs┬, ┬ServerlistMOTD*┬, ┬ServerRestorer┬, ┬SkinsRestorer┬, ┬Skript┬, ┬SpigotPing*┬, ┬Spleef*┬, ┬Vault┬, ┬VoidGenerator┬, ┬Votifier┬, ┬VotingPlugin┬, ┬WorldBorder┬, ┬WorldEdit

**Console log:**
<details>
  <summary>Log</summary>
  
   ```
Could not pass event PlayerInteractEntityEvent to BedWars v0.2.1
java.lang.RuntimeException: Invalid operation: There are two operands without operator!
	at misat11.bw.lib.sgui.operations.OperationParser.internalProcess(OperationParser.java:250) ~[?:?]
	at misat11.bw.lib.sgui.operations.OperationParser.getFinalOperation(OperationParser.java:170) ~[?:?]
	at misat11.bw.lib.sgui.SimpleGuiFormat.processPlaceholders(SimpleGuiFormat.java:235) ~[?:?]
	at misat11.bw.lib.sgui.GuiHolder.repaint(GuiHolder.java:122) ~[?:?]
	at misat11.bw.lib.sgui.GuiHolder.<init>(GuiHolder.java:48) ~[?:?]
	at misat11.bw.lib.sgui.SimpleGuiFormat.openForPlayer(SimpleGuiFormat.java:661) ~[?:?]
	at misat11.bw.utils.ShopMenu.show(ShopMenu.java:348) ~[?:?]
	at misat11.bw.Main.openStore(Main.java:201) ~[?:?]
	at misat11.bw.listener.VillagerListener.onVillagerInteract(VillagerListener.java:36) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor268.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-214]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-214]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-214]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1983) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-214]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-214]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
</details>
**Configuration (of config.yml and shop.yml):**
<details>
  <summary>Config.yml</summary>
  locale: cs
allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true
friendlyfire: false
player-drops: true
join-randomly-after-lobby-timeout: false
spectator-gm3: true
prevent-killing-villagers: true
compass-enabled: true
join-randomly-on-lobby-join: false
add-wool-to-inventory-on-join: true
prevent-spawning-mobs: true
spawner-holograms: true
spawner-disable-merge: true
prevent-lobby-spawn-mobs-in-radius: 16
spawner-holo-height: 0.25
spawner-holograms-countdown: true
damage-when-player-is-not-in-arena: false
remove-unused-target-blocks: true
allow-block-falling: true
game-start-items: false
player-respawn-items: false
gived-game-start-items: []
gived-player-respawn-items: []
disable-hunger: false
automatic-coloring-in-shop: true
sell-max-64-per-click-in-shop: true
destroy-placed-blocks-by-explosion: true
holo-above-bed: true
allowed-commands: []
change-allowed-commands-to-blacklist: false
bungee:
  enabled: false
  serverRestart: true
  serverStop: false
  server: hub
  auto-game-connect: false
farmBlocks:
  enable: true
  blocks: []
scoreboard:
  enable: true
  title: §a%game%§r - %time%
  bedLost: §c✘
  bedExists: §a✔
  teamTitle: '%bed%%color%%team%'
title:
  fadeIn: 0
  stay: 20
  fadeOut: 0
items:
  jointeam: COMPASS
  leavegame: SLIME_BALL
  startgame: DIAMOND
  shopback: BARRIER
  shopcosmetic: GRAY_STAINED_GLASS_PANE
  pageback: ARROW
  pageforward: ARROW
vault:
  enable: true
  reward:
    kill: 10
    win: 20
resources:
  diamond:
    material: DIAMOND
    color: BLUE
    name: Diamant
    interval: 45
    translate: resource_diamond
    spread: 1.0
  gold:
    material: GOLD_INGOT
    color: GOLD
    name: Zlato
    interval: 20
    translate: resource_gold
    spread: 1.0
  iron:
    material: IRON_INGOT
    color: GRAY
    name: Zelezo
    interval: 10
    translate: resource_iron
    spread: 1.0
  bronze:
    material: BRICK
    color: DARK_RED
    name: Bronz
    interval: 1
    translate: resource_bronze
    spread: 1.0
respawn:
  protection-enabled: true
  protection-time: 10
specials:
  action-bar-messages: true
  rescue-platform:
    is-breakable: false
    delay: 0
    break-time: 10
    distance: 1
    material: GLASS
  protection-wall:
    is-breakable: false
    delay: 20
    break-time: 0
    width: 5
    height: 3
    distance: 2
    material: CUT_SANDSTONE
  tnt-sheep:
    speed: 2.0
    follow-range: 10.0
    max-target-distance: 32
    explosion-time: 8
  arrow-blocker:
    protection-time: 10
    delay: 5
  warp-powder:
    teleport-time: 6
    delay: 0
  magnet-shoes:
    probability: 75
  golem:
    speed: 0.25
    follow-range: 10
    health: 20
    name-format: '%teamcolor%%team% Golem'
    show-name: true
    delay: 0
    collidable: false
  tntsheep:
    explosion-time: 8
tnt:
  auto-ignite: false
  explosion-time: 8
sounds:
  on_bed_destroyed: ENTITY_ENDER_DRAGON_GROWL
  on_countdown: UI_BUTTON_CLICK
  on_game_start: ENTITY_PLAYER_LEVELUP
  on_team_kill: ENTITY_PLAYER_LEVELUP
  on_player_kill: ENTITY_PLAYER_BIG_FALL
  on_item_buy: ENTITY_ITEM_PICKUP
  on_upgrade_buy: ENTITY_EXPERIENCE_ORB_PICKUP
game-effects:
  end:
    effects:
    - ==: Firework
      flicker: false
      trail: false
      colors:
      - &id001
        ==: Color
        RED: 255
        BLUE: 255
        GREEN: 255
      fade-colors:
      - *id001
      type: BALL
    power: 1
    type: Firework
  start: {}
  kill: {}
  teamkill: {}
  lobbyjoin: {}
  lobbyleave: {}
  respawn: {}
  beddestroy: {}
  warppowdertick: {}
lobby-scoreboard:
  enabled: true
  title: §eBEDWARS
  content:
  - ' '
  - '§fMapa: §2%arena%'
  - '§fHraci: §2%players%§f/§2%maxplayers%'
  - ' '
  - §fCekam...
  - ' '
statistics:
  enabled: true
  type: yaml
  show-on-game-end: false
  bed-destroyed-kills: false
  scores:
    kill: 10
    die: 0
    win: 50
    bed-destroy: 25
    lose: 0
    record: 100
database:
  host: localhost
  port: 3306
  db: databse
  user: root
  password: secret
  table-prefix: bw_
bossbar:
  use-xp-bar: false
  lobby:
    enable: true
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: true
    color: GREEN
    style: SEGMENTED_20
holograms:
  enabled: true
  headline: Your §eBEDWARS§f stats
chat:
  override: true
  format: '<%teamcolor%%name%§r> '
  separate-game-chat: false
  send-death-messages-just-in-game: true
  send-custom-death-messages: true
  default-team-chat-while-running: true
  all-chat-prefix: '!'
  team-chat-prefix: '@t'
  all-chat: '[ALL] '
  team-chat: '[TEAM] '
  death-chat: '[DEATH] '
rewards:
  enabled: false
  player-win:
  - /example {player} 200
  player-end-game:
  - /example {player} {score}
  player-destroy-bed:
  - /example {player} {score}
  player-kill:
  - /example {player} 10
lore:
  generate-automatically: true
  text:
  - '§7Price:'
  - §7%price% %resource%
  - '§7Amount:'
  - §7%amount%
sign:
- §c§l[BedWars]
- '%arena%'
- '%status%'
- '%players%'
hotbar:
  selector: 0
  color: 1
  start: 2
  leave: 8
breakable:
  enabled: false
  blocks: []
version: 2

</details>
<details>
  <summary>Shop.yml</summary>
  # DO NOT EDIT THIS VARIABLE!!!
version: 2

# And this you can edit of course.
data:
#-   stack:
#      ==: org.bukkit.inventory.ItemStack 
#      v: 1519
#      type: GOLDEN_APPLE
#      amount: 1
#      meta:
#        ==: ItemMeta
#        meta-type: UNSPECIFIC
#        display-name: "Example category"
#        lore:
#        - "This is my category!"
#        - "Please buy things inside!"
#    items:
#    - price: 50
#      price-type: "bronze"
#      stack:
#        ==: org.bukkit.inventory.ItemStack
#        v: 1519
#        type: DIAMOND_SWORD
#        amount: 1
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          enchants:
#            DAMAGE_ALL: 2
#          repair-cost: 1
#          Damage: 99
# Value 'applycolorbyteam' is used for automatic-coloring-in-shop.
# See WarpPowder for more info.

-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: DIAMOND_CHESTPLATE
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Brnění"
        lore:
        - "Zeslabení síly útoků"
    items:
    - price: 1
      price-type: bronze
      properties:
        - name: "applycolorbyteam"
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_HELMET
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price: 1
      price-type: bronze
      properties:
        - name: "applycolorbyteam"
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_LEGGINGS
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price: 1
      price-type: bronze
      properties:
        - name: "applycolorbyteam"
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: LEATHER_BOOTS
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price: 1
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CHAINMAIL_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price: 3
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CHAINMAIL_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 7
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CHAINMAIL_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 3
    - price: 10
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_HELMET
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Helma
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 2
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Legendární brnění
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price: 3
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_CHESTPLATE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: Legendární brnění MKII
          enchants:
            PROTECTION_ENVIRONMENTAL: 3
  
-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: DIAMOND_SWORD
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Meče"
        lore:
        - "Určené pro útok na blízko"
    column: center
    items:
    - price: 8
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: STICK
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 1
    - price: 1
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_SWORD   
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
    - price: 3
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_SWORD   
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
    - price: 7
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_SWORD   
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 3
    - price: 3
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_SWORD   
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
            KNOCKBACK: 1
    - price: 15
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_AXE
        display-name: "Sekera Nekonečnosti"
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
            DURABILITY: 1
            KNOCKBACK: 1
    - price: 2
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_SWORD
        display-name: "Legendární meč"
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
            DURABILITY: 1
            KNOCKBACK: 2
            FIRE_ASPECT: 1
    
-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: BOW
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Luky"
        lore:
        - "Zbraně na větší vzdálenost"
    column: right
    items:
    - price: 3
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
    - price: 7
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
            ARROW_DAMAGE: 1
    - price: 13
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
            ARROW_DAMAGE: 2
    - price: 14
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
            ARROW_FIRE: 1
    - price: 15
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
            ARROW_FIRE: 1
            ARROW_KNOCKBACK: 1
    - price: 3
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BOW
        amount: 1
        display-name: "Legendární luk"
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_INFINITE: 1
            ARROW_FIRE: 1
            ARROW_KNOCKBACK: 2
            ARROW_DAMAGE: 3
    - price: 1
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: ARROW
        amount: 1 
        
-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: COOKED_PORKCHOP
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Jídlo"
        lore:
        - "Dobré na regeneraci zdraví"
    row: 3
    column: 2
    items:
    - price: 4
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: COOKED_PORKCHOP
        amount: 2
    - price: 2
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GOLDEN_APPLE
        amount: 1
    - price: 5
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: BREAD
        amount: 10
    - price: 2
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: ENCHANTED_GOLDEN_APPLE
        amount: 1

-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: POTION
      meta:
        ==: ItemMeta
        meta-type: POTION
        display-name: "Lektvary"
        lore:
        - "Dobré na extra efekty!"
        potion-type: strength
    row: 3
    column: 6
    items:
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: healing
      price: 3
      price-type: iron
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: strong_healing
      price: 5
      price-type: iron
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: swiftness
      price: 7
      price-type: iron
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: strength
      price: 1
      price-type: gold
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: regeneration
      price: 2
      price-type: diamond
    - stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: haste
      
        

-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: SANDSTONE
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Bloky"
        lore:
        - "Na vytváření mostů a ochrany postele"
    linebreak: before
    items:
    - price: 1
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CUT_SANDSTONE
        amount: 2
    - price: 7
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: END_STONE
        amount: 3
    - price: 3
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_BLOCK
        amount: 1
    - price: 15
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GLOWSTONE
        amount: 4
    - price: 4
      price-type: bronze
      properties:
        - name: "applycolorbyteam"
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: GLASS
    - price: 5
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: OBSIDIAN
            
-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: TNT
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Různé věci"
        lore:
        - "Různé věci na vylepšení hry!"
    column: center
    items:
    - price: 1
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: CHEST
    - price: 1
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: ENDER_CHEST
    - price: 7
      price-type: iron
      properties:
      - name: "WarpPowder"
        delay: 6
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: GUNPOWDER
        v: 1519
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "WarPRach"
          lore:
          - "Tímto se teleportujete na spawnpoint"
          - "Musíte počkat 6 sekund"
          - "Jakýkoliv pohyb zruší teleportaci"
    - price: 3
      price-type: iron
      properties:
      - name: "Past"
        data:
        - sound: ENTITY_SHEEP_AMBIENT
        - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 15
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
        - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 18
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
        - effect:
            ==: org.bukkit.potion.PotionEffect
            effect: 2
            amplifier: 2
            duration: 100
            ambient: true
            has-particles: true
            has-icon: true
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: STRING
        v: 1519
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "Past"
          lore:
          - "Když ji překročí nepřátel, dozvíte se o tom"
          - "Nepřátel bude také zpomalen"
    - price: 6
      price-type: iron
      properties:
        - name: "MagnetShoes"
          probability: 75
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: IRON_BOOTS
        v: 1519
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "MagnetBoty"
          lore:
            - "Máte 75% šanci na žádný knockback!"
    - price: 5
      price-type: iron
      properties:
        - name: "Tracker"
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: COMPASS
        v: 1519
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "Sledovací zařízení"
          lore:
            - "Chcete vědět, kde je váš nepřátel?"
            - "Zkuste to!"
    - price: 15
      price-type: iron
      properties:
        - name: "rescueplatform"
          delay: 5
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: BLAZE_ROD
        v: 1519
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "Záchranná plocha"
          lore:
            - "Zruší pád do voidu"
            - "Dá pod vás podlahu."
    - price: 10
      price-type: gold
      properties:
        - name: "arrowblocker"
          delay: 5
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: ENDER_EYE
        v: 1519
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "Blokace šípů"
          lore:
            - "Zablokuje šípy, které"
            - "letí na vás"
    - price: 64
      price-type: bronze
      properties:
        - name: "protectionwall"
      stack:
        ==: org.bukkit.inventory.ItemStack
        type: BRICKS
        v: 1519
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: "InstaZeď"
          lore:
            - "Postaví před vás zeď"
    - price: 10
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: SHIELD
    - price: 1
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: TOTEM_OF_UNDYING

-   stack:
      ==: org.bukkit.inventory.ItemStack
      v: 1519
      type: DIAMOND_PICKAXE
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "Krumpáče"
        lore:
        - "Na zničení bloků"
    column: right
    items:
    - price: 4
      price-type: bronze
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 1
    - price: 2
      price-type: iron
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 2
            DIG_SPEED: 1
    - price: 2
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: IRON_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            LOOT_BONUS_BLOCKS: 3
            DIG_SPEED: 2
    - price: 15
      price-type: gold
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
    - price: 1
      price-type: diamond
      stack:
        ==: org.bukkit.inventory.ItemStack
        v: 1519
        type: DIAMOND_PICKAXE
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            

</details>

**If there are problem with only one game, paste here config of this game:**

**Comment by tjd2** [comment]
Information!
Apparently, the bug is caused by Spigot function change (commit 683bae0670c), which was recently reverted.
We should wait for next paper release.
Should i already close it?
